	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 00
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 01
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 02
	tilecoll TALL_GRASS, TALL_GRASS, TALL_GRASS, TALL_GRASS ; 03
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 04
	tilecoll WALL, WALL, WALL, WALL ; 05
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 06
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 07
	tilecoll WALL, WALL, WALL, WALL ; 08
	tilecoll WALL, WALL, WALL, WALL ; 09
	tilecoll WALL, WALL, WALL, WALL ; 0a
	tilecoll WARP_CARPET_LEFT, FLOOR, WARP_CARPET_LEFT, FLOOR ; 0b
	tilecoll FLOOR, FLOOR, WALL, WARP_CARPET_DOWN ; 0c
	tilecoll FLOOR, FLOOR, WARP_CARPET_DOWN, WALL ; 0d
	tilecoll FLOOR, WARP_CARPET_RIGHT, FLOOR, WARP_CARPET_RIGHT ; 0e
	tilecoll WALL, WALL, WALL, WALL ; 0f
	tilecoll WALL, WALL, WALL, WALL ; 10
	tilecoll WALL, WALL, WALL, WALL ; 11
	tilecoll WALL, WALL, WALL, WALL ; 12
	tilecoll WALL, WALL, WALL, WALL ; 13
	tilecoll WALL, WALL, WALL, DOOR ; 14
	tilecoll WALL, WALL, WALL, WALL ; 15
	tilecoll WALL, WALL, WALL, DOOR ; 16
	tilecoll WALL, WALL, DOOR, WALL ; 17
	tilecoll WALL, WALL, WALL, WALL ; 18
	tilecoll WALL, WALL, WALL, WALL ; 19
	tilecoll WALL, WALL, WALL, DOOR ; 1a
	tilecoll WALL, WALL, POKECENTER_SIGN, WALL ; 1b
	tilecoll WALL, WALL, WALL, WALL ; 1c
	tilecoll WALL, WALL, DOOR, WALL ; 1d
	tilecoll WALL, WALL, WALL, WALL ; 1e
	tilecoll WALL, WALL, WALL, WALL ; 1f
	tilecoll SNOW, SNOW, SNOW, SNOW ; 20
	tilecoll WALL, WALL, WALL, WALL ; 21
	tilecoll WALL, WALL, WALL, WALL ; 22
	tilecoll WALL, WALL, WALL, WALL ; 23
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 24
	tilecoll WALL, WALL, WALL, WALL ; 25
	tilecoll WALL, WALL, WALL, WALL ; 26
	tilecoll WALL, WALL, WALL, WALL ; 27
	tilecoll WALL, WALL, WALL, WALL ; 28
	tilecoll WALL, WALL, WALL, WALL ; 29
	tilecoll WALL, WALL, WALL, WALL ; 2a
	tilecoll WALL, WALL, WALL, WALL ; 2b
	tilecoll WALL, WALL, WALL, WALL ; 2c
	tilecoll WALL, WALL, WALL, DOOR ; 2d
	tilecoll WALL, WALL, WALL, WALL ; 2e
	tilecoll HEADBUTT_TREE, HEADBUTT_TREE, FLOOR, FLOOR ; 2f
	tilecoll BUOY, BUOY, BUOY, WATER ; 30
	tilecoll BUOY, BUOY, WATER, WATER ; 31
	tilecoll BUOY, BUOY, WATER, BUOY ; 32
	tilecoll WALL, WALL, MART_SIGN, WALL ; 33
	tilecoll BUOY, WATER, BUOY, WATER ; 34
	tilecoll WATER, WATER, WATER, WATER ; 35
	tilecoll WATER, BUOY, WATER, BUOY ; 36
	tilecoll HEADBUTT_TREE, FLOOR, FLOOR, FLOOR ; 37
	tilecoll BUOY, WATER, BUOY, BUOY ; 38
	tilecoll WATER, WATER, BUOY, BUOY ; 39
	tilecoll WATER, BUOY, BUOY, BUOY ; 3a
	tilecoll FLOOR, FLOOR, HEADBUTT_TREE, HEADBUTT_TREE ; 3b
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 3c
	tilecoll HEADBUTT_TREE, HEADBUTT_TREE, WALL, WALL ; 3d
	tilecoll SNOW, SNOW, SNOW, FLOOR ; 3e
	tilecoll HEADBUTT_TREE, HEADBUTT_TREE, HEADBUTT_TREE, HEADBUTT_TREE ; 3f
	tilecoll WALL, WALL, WALL, FLOOR ; 40
	tilecoll WALL, WALL, FLOOR, FLOOR ; 41
	tilecoll WALL, WALL, FLOOR, WALL ; 42
	tilecoll WATER, WATER, WATER, WATER ; 43
	tilecoll WALL, FLOOR, WALL, FLOOR ; 44
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 45
	tilecoll FLOOR, WALL, FLOOR, WALL ; 46
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 47
	tilecoll WALL, FLOOR, WALL, WALL ; 48
	tilecoll FLOOR, FLOOR, WALL, WALL ; 49
	tilecoll FLOOR, WALL, WALL, WALL ; 4a
	tilecoll LEDGE_DOWN, FLOOR, WALL, FLOOR ; 4b
	tilecoll WALL, LEDGE_LEFT, WALL, LEDGE_LEFT ; 4c
	tilecoll LEDGE_RIGHT, WALL, LEDGE_RIGHT, WALL ; 4d
	tilecoll WALL, LEDGE_LEFT, WALL, LEDGE_LEFT ; 4e
	tilecoll LEDGE_RIGHT, WALL, LEDGE_RIGHT, WALL ; 4f
	tilecoll WALL, LEDGE_DOWN_LEFT, WALL, WALL ; 50
	tilecoll LEDGE_DOWN_RIGHT, WALL, WALL, WALL ; 51
	tilecoll WALL, LEDGE_DOWN_LEFT, WALL, WALL ; 52
	tilecoll LEDGE_DOWN_RIGHT, WALL, WALL, WALL ; 53
	tilecoll WATER, WATER, WATER, WATER ; 54
	tilecoll WATER, WATER, WATER, WATER ; 55
	tilecoll LEDGE_DOWN, LEDGE_DOWN, WALL, WALL ; 56
	tilecoll LEDGE_DOWN, LEDGE_DOWN, WALL, WALL ; 57
	tilecoll WATER, WATER, WATER, WATER ; 58
	tilecoll WATER, WATER, WATER, WATER ; 59
	tilecoll LEDGE_DOWN, FLOOR, WALL, FLOOR ; 5a
	tilecoll SNOW, SNOW, SNOW, FLOOR ; 5b
	tilecoll SNOW, SNOW, FLOOR, SNOW ; 5c
	tilecoll SNOW, SNOW, FLOOR, SNOW ; 5d
	tilecoll FLOOR, TALL_GRASS, TALL_GRASS, TALL_GRASS ; 5e
	tilecoll TALL_GRASS, FLOOR, TALL_GRASS, TALL_GRASS ; 5f
	tilecoll SNOW, FLOOR, SNOW, SNOW ; 60
	tilecoll WATER, WATER, WALL, WALL ; 61
	tilecoll FLOOR, SNOW, SNOW, SNOW ; 62
	tilecoll WATER, WATER, WATER, WATER ; 63
	tilecoll FLOOR, WALL, FLOOR, WALL ; 64
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 65
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 66
	tilecoll WALL, WALL, WALL, WALL ; 67
	tilecoll WALL, FLOOR, WALL, FLOOR ; 68
	tilecoll FLOOR, WALL, FLOOR, WALL ; 69
	tilecoll WALL, TOP_WALL, WALL, FLOOR ; 6a
	tilecoll TOP_WALL, WALL, FLOOR, WALL ; 6b
	tilecoll WALL, FLOOR, WALL, WALL ; 6c
	tilecoll FLOOR, WALL, WALL, WALL ; 6d
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 6e
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 6f
	tilecoll TOP_WALL, TOP_WALL, FLOOR, FLOOR ; 70
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 71
	tilecoll FLOOR, FLOOR, WALL, WALL ; 72
	tilecoll FLOOR, FLOOR, WALL, CAVE ; 73
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 74
	tilecoll WALL, WALL, FLOOR, FLOOR ; 75
	tilecoll WATER, WATER, WATER, WATER ; 76
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 77
	tilecoll WALL, WALL, WALL, WALL ; 78
	tilecoll WATER, WATER, WATER, WATER ; 79
	tilecoll WATER, WATER, WATER, WATER ; 7a
	tilecoll WALL, WALL, WALL, WALL ; 7b
	tilecoll WALL, WALL, WALL, WALL ; 7c
	tilecoll WALL, WALL, WALL, WALL ; 7d
	tilecoll WALL, WALL, WALL, WALL ; 7e
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 7f
	tilecoll WALL, LEDGE_DOWN_LEFT, WALL, WALL ; 80
	tilecoll LEDGE_DOWN, LEDGE_DOWN, WALL, WALL ; 81
	tilecoll LEDGE_DOWN_RIGHT, WALL, WALL, WALL ; 82
	tilecoll FLOOR, LEDGE_DOWN, FLOOR, WALL ; 83
	tilecoll WALL, LEDGE_LEFT, WALL, FLOOR ; 84
	tilecoll LEDGE_RIGHT, WALL, FLOOR, WALL ; 85
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 86
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 87
	tilecoll ICE, ICE, ICE, ICE ; 88
	tilecoll ICE, ICE, WALL, WALL ; 89
	tilecoll ICE, WALL, WALL, WALL ; 8a
	tilecoll WALL, ICE, WALL, WALL ; 8b
	tilecoll WALL, ICE, WALL, ICE ; 8c
	tilecoll ICE, WALL, ICE, WALL ; 8d
	tilecoll ICE, ICE, ICE, WALL ; 8e
	tilecoll ICE, ICE, WALL, ICE ; 8f
	tilecoll WALL, ICE, ICE, ICE ; 90
	tilecoll ICE, WALL, ICE, ICE ; 91
	tilecoll ICE, WALL, FLOOR, WALL ; 92
	tilecoll WALL, ICE, WALL, FLOOR ; 93
	tilecoll ICE, ICE, WALL, FLOOR ; 94
	tilecoll SNOW, ICE, ICE, ICE ; 95
	tilecoll ICE, ICE, SNOW, ICE ; 96
	tilecoll ICE, SNOW, ICE, ICE ; 97
	tilecoll ICE, ICE, ICE, SNOW ; 98
	tilecoll FLOOR, FLOOR, WALL, WALL ; 99
	tilecoll WALL, WALL, WALL, WALL ; 9a
	tilecoll WALL, WALL, WALL, ICE ; 9b
	tilecoll WALL, WALL, WALL, WALL ; 9c
	tilecoll WALL, WALL, ICE, ICE ; 9d
	tilecoll WALL, FLOOR, WALL, WALL ; 9e
	tilecoll ICE, WALL, WALL, WALL ; 9f
	tilecoll WALL, WALL, WALL, ICE ; a0
	tilecoll WALL, WALL, WALL, WALL ; a1
	tilecoll WALL, WALL, WALL, WALL ; a2
	tilecoll WALL, WALL, WALL, CAVE ; a3
	tilecoll SNOW, ICE, SNOW, ICE ; a4
	tilecoll ICE, SNOW, ICE, SNOW ; a5
	tilecoll WALL, WALL, WALL, WALL ; a6
	tilecoll WALL, WALL, WALL, WALL ; a7
	tilecoll WALL, WALL, WALL, WALL ; a8
	tilecoll WALL, WALL, WALL, WALL ; a9
	tilecoll WALL, WALL, WALL, WALL ; aa
	tilecoll WALL, WALL, WALL, FLOOR ; ab
	tilecoll WALL, WALL, WALL, WALL ; ac
	tilecoll WALL, WALL, WALL, WALL ; ad
	tilecoll WALL, WALL, WALL, WALL ; ae
	tilecoll WALL, WALL, FLOOR, FLOOR ; af
	tilecoll WALL, WALL, WALL, WALL ; b0
	tilecoll WALL, WALL, WALL, WALL ; b1
	tilecoll WALL, WALL, WALL, WALL ; b2
	tilecoll WALL, WALL, WALL, WALL ; b3
	tilecoll WALL, WALL, WALL, WALL ; b4
	tilecoll WATER, WALL, WALL, WALL ; b5
	tilecoll WALL, WATER, WALL, WALL ; b6
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; b7
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; b8
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; b9
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; ba
	tilecoll WALL, WALL, WALL, WALL ; bb
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; bc
	tilecoll WALL, WALL, FLOOR, FLOOR ; bd
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; be
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; bf
	tilecoll FLOOR, WALL, FLOOR, WALL ; c0
	tilecoll WALL, FLOOR, WALL, FLOOR ; c1
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; c2
	tilecoll FLOOR, FLOOR, TOP_WALL, TOP_WALL ; c3
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; c4
	tilecoll WALL, TOP_WALL, WALL, WALL ; c5
	tilecoll TOP_WALL, TOP_WALL, TOP_WALL, TOP_WALL ; c6
	tilecoll TOP_WALL, TOP_WALL, WALL, FLOOR ; c7
	tilecoll WALL, WALL, FLOOR, WALL ; c8
	tilecoll FLOOR, WALL, WALL, WALL ; c9
	tilecoll TOP_WALL, TOP_WALL, FLOOR, WALL ; ca
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; cb
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; cc
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; cd
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; ce
	tilecoll FLOOR, WATER, FLOOR, WATER ; cf
	tilecoll WATER, FLOOR, WATER, FLOOR ; d0
	tilecoll WALL, WATER, WALL, WATER ; d1
	tilecoll FLOOR, WATER, FLOOR, WATER ; d2
	tilecoll WATER, WATER, WATER, WATER ; d3
	tilecoll WALL, WALL, WALL, WALL ; d4
	tilecoll WALL, WALL, WALL, WALL ; d5
