	tilecoll WALL, WALL, WALL, WALL ; 00
	tilecoll FLOOR, FLOOR, WARP_CARPET_DOWN, WARP_CARPET_DOWN ; 01
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 02
	tilecoll WALL, WALL, WALL, WALL ; 03
	tilecoll WALL, WALL, FLOOR, FLOOR ; 04
	tilecoll WALL, WALL, FLOOR, FLOOR ; 05
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 06
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 07
	tilecoll FLOOR, WALL, FLOOR, WALL ; 08
	tilecoll FLOOR, WALL, FLOOR, WALL ; 09
	tilecoll FLOOR, WALL, FLOOR, WALL ; 0a
	tilecoll FLOOR, WALL, FLOOR, WALL ; 0b
	tilecoll WALL, WALL, WALL, WALL ; 0c
	tilecoll WALL, WALL, WALL, WALL ; 0d
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 0e
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 0f
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 10
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 11
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 12
	tilecoll WALL, WALL, WALL, WALL ; 13
	tilecoll FLOOR, FLOOR, WALL, WALL ; 14
	tilecoll WALL, WALL, FLOOR, FLOOR ; 15
	tilecoll FLOOR, WALL, FLOOR, WALL ; 16
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 17
	tilecoll WALL, FLOOR, FLOOR, WALL ; 18
	tilecoll WALL, WALL, FLOOR, WARP_PANEL ; 19
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 1a
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 1b
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 1c
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 1d
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 1e
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 1f
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 20
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 21
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 22
	tilecoll FLOOR, FLOOR, FLOOR, WARP_PANEL ; 23
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 24
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 25
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 26
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 27
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 28
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 29
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 2a
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 2b
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 2c
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 2d
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 2e
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 2f
	tilecoll FLOOR, WALL, WALL, WALL ; 30
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 31
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 32
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 33
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 34
	tilecoll FLOOR, FLOOR, WARP_CARPET_DOWN, WARP_CARPET_DOWN ; 35
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 36
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 37
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 38
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 39
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 3a
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 3b
	tilecoll WALL, WALL, WALL, FLOOR ; 3c
	tilecoll WALL, WALL, FLOOR, FLOOR ; 3d
	tilecoll WALL, FLOOR, WALL, FLOOR ; 3e
	tilecoll WALL, FLOOR, WALL, FLOOR ; 3f
	tilecoll WALL, WALL, FLOOR, WALL ; 40
	tilecoll FLOOR, WALL, FLOOR, WALL ; 41
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 42
	tilecoll WALL, WALL, FLOOR, FLOOR ; 43
	tilecoll WALL, WALL, FLOOR, FLOOR ; 44
	tilecoll WALL, WALL, FLOOR, FLOOR ; 45
	tilecoll WALL, WALL, FLOOR, FLOOR ; 46
	tilecoll WALL, WALL, FLOOR, FLOOR ; 47
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 48
	tilecoll WALL, WALL, FLOOR, FLOOR ; 49
	tilecoll FLOOR, WALL, FLOOR, WALL ; 4a
	tilecoll WALL, FLOOR, WALL, FLOOR ; 4b
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 4c
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 4d
	tilecoll FLOOR, FLOOR, LADDER, FLOOR ; 4e
	tilecoll WALL, WALL, WALL, WALL ; 4f
	tilecoll WALL, WALL, WALL, FLOOR ; 50
	tilecoll WALL, WALL, WALL, WALL ; 51
	tilecoll LADDER, FLOOR, FLOOR, FLOOR ; 52
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 53
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 54
	tilecoll WALL, WALL, WALL, WALL ; 55
	tilecoll WALL, WALL, WALL, WALL ; 56
	tilecoll WALL, WALL, FLOOR, WALL ; 57
	tilecoll WALL, WALL, FLOOR, WALL ; 58
	tilecoll FLOOR, WALL, FLOOR, WALL ; 59
	tilecoll WALL, WALL, WALL, FLOOR ; 5a
	tilecoll WALL, WALL, FLOOR, WALL ; 5b
	tilecoll WALL, WALL, WALL, FLOOR ; 5c
	tilecoll WALL, WALL, FLOOR, FLOOR ; 5d
	tilecoll WALL, WALL, WALL, WALL ; 5e
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 5f
	tilecoll WALL, WALL, WALL, FLOOR ; 60
	tilecoll WALL, WALL, FLOOR, FLOOR ; 61
	tilecoll WALL, WALL, FLOOR, WALL ; 62
	tilecoll WALL, FLOOR, WALL, WALL ; 63
	tilecoll FLOOR, FLOOR, WALL, WALL ; 64
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 65
	tilecoll FLOOR, WALL, WALL, WALL ; 66
	tilecoll FLOOR, FLOOR, WALL, WALL ; 67
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 68
	tilecoll WALL, WALL, FLOOR, WALL ; 69
	tilecoll WALL, WALL, WALL, WALL ; 6a
	tilecoll WALL, WALL, WALL, WALL ; 6b
	tilecoll WALL, WALL, WALL, WALL ; 6c
	tilecoll WALL, WALL, WALL, WALL ; 6d
	tilecoll WALL, WALL, WALL, WALL ; 6e
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 6f
	tilecoll WALL, WALL, FLOOR, FLOOR ; 70
	tilecoll WALL, WALL, WALL, WALL ; 71
	tilecoll WALL, WALL, WALL, WALL ; 72
	tilecoll WALL, WALL, WALL, WALL ; 73
	tilecoll WALL, WALL, WALL, WALL ; 74
	tilecoll WALL, WALL, WALL, WALL ; 75
	tilecoll WALL, WALL, WALL, WALL ; 76
	tilecoll WALL, WALL, WALL, WALL ; 77
	tilecoll WALL, WALL, WALL, WALL ; 78
	tilecoll WALL, WATER, WALL, WATER ; 79
	tilecoll WATER, WATER, WATER, WATER ; 7a
	tilecoll WALL, WALL, WALL, FLOOR ; 7b
	tilecoll WALL, WALL, WALL, FLOOR ; 7c
	tilecoll WALL, FLOOR, WALL, FLOOR ; 7d
	tilecoll WALL, WALL, FLOOR, FLOOR ; 7e
	tilecoll FLOOR, FLOOR, WALL, WALL ; 7f
	tilecoll WALL, WALL, FLOOR, FLOOR ; 80
	tilecoll FLOOR, WALL, WALL, WALL ; 81
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 82
	tilecoll WALL, WALL, FLOOR, FLOOR ; 83
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 84
	tilecoll WALL, FLOOR, WALL, FLOOR ; 85
	tilecoll WALL, WALL, WALL, WALL ; 86
	tilecoll ICE, ICE, ICE, ICE ; 87
	tilecoll WALL, WALL, FLOOR, FLOOR ; 88
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 89
	tilecoll FLOOR, FLOOR, WALL, WALL ; 8a
	tilecoll WALL, WALL, FLOOR, FLOOR ; 8b
	tilecoll LADDER, FLOOR, FLOOR, FLOOR ; 8c
	tilecoll WALL, WALL, WALL, WALL ; 8d
	tilecoll WALL, WALL, WALL, WALL ; 8e
	tilecoll FLOOR, WALL, FLOOR, WALL ; 8f
	tilecoll WALL, FLOOR, WALL, FLOOR ; 90
	tilecoll FLOOR, WALL, FLOOR, WALL ; 91
	tilecoll WALL, FLOOR, WALL, FLOOR ; 92
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 93
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 94
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 95
	tilecoll WALL, FLOOR, WALL, FLOOR ; 96
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 97
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 98
	tilecoll WALL, FLOOR, WALL, FLOOR ; 99
	tilecoll FLOOR, WALL, FLOOR, WALL ; 9a
