	tilecoll WALL, WALL, WALL, WALL ; 00
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 01
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 02
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 03
	tilecoll WALL, WALL, WALL, WALL ; 04
	tilecoll WALL, WALL, WALL, WALL ; 05
	tilecoll WALL, WALL, WALL, WALL ; 06
	tilecoll WALL, WALL, WALL, WALL ; 07
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 08
	tilecoll FLOOR, FLOOR, FLOOR, LADDER ; 09
	tilecoll FLOOR, FLOOR, FLOOR, LADDER ; 0a
	tilecoll WALL, WALL, WALL, WALL ; 0b
	tilecoll WALL, WALL, WALL, WALL ; 0c
	tilecoll WALL, WALL, WALL, WALL ; 0d
	tilecoll WALL, WALL, WALL, WALL ; 0e
	tilecoll WALL, WALL, WALL, WALL ; 0f
	tilecoll TOP_WALL, TOP_WALL, FLOOR, FLOOR ; 10
	tilecoll WALL, FLOOR, WALL, FLOOR ; 11
	tilecoll FLOOR, WALL, FLOOR, WALL ; 12
	tilecoll FLOOR, FLOOR, WARP_CARPET_DOWN, WARP_CARPET_DOWN ; 13
	tilecoll FLOOR, FLOOR, WALL, WALL ; 14
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 15
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 16
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 17
	tilecoll WALL, WALL, WALL, WALL ; 18
	tilecoll FLOOR, FLOOR, CAVE, WALL ; 19
	tilecoll FLOOR, OASIS, FLOOR, FLOOR ; 1a
	tilecoll OASIS, OASIS, FLOOR, FLOOR ; 1b
	tilecoll OASIS, FLOOR, FLOOR, FLOOR ; 1c
	tilecoll OASIS, FLOOR, OASIS, FLOOR ; 1d
	tilecoll FLOOR, OASIS, FLOOR, OASIS ; 1e
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 1f
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 20
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 21
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 22
	tilecoll WALL, WALL, FLOOR, FLOOR ; 23
	tilecoll FLOOR, FLOOR, WALL, WALL ; 24
	tilecoll FLOOR, WALL, FLOOR, WALL ; 25
	tilecoll WALL, FLOOR, WALL, FLOOR ; 26
	tilecoll WALL, WALL, WALL, FLOOR ; 27
	tilecoll WALL, WALL, FLOOR, WALL ; 28
	tilecoll WALL, FLOOR, WALL, WALL ; 29
	tilecoll FLOOR, WALL, WALL, WALL ; 2a
	tilecoll FLOOR, FLOOR, WALL, WALL ; 2b
	tilecoll FLOOR, FLOOR, WALL, WALL ; 2c
	tilecoll FLOOR, FLOOR, WALL, WALL ; 2d
	tilecoll FLOOR, WALL, FLOOR, WALL ; 2e
	tilecoll FLOOR, WALL, FLOOR, WALL ; 2f
	tilecoll WALL, WALL, WALL, WALL ; 30
	tilecoll WALL, WALL, WALL, WALL ; 31
	tilecoll WALL, WALL, WALL, WALL ; 32
	tilecoll HOLE, FLOOR, FLOOR, FLOOR ; 33
	tilecoll FLOOR, HOLE, FLOOR, FLOOR ; 34
	tilecoll FLOOR, FLOOR, HOLE, FLOOR ; 35
	tilecoll FLOOR, FLOOR, FLOOR, HOLE ; 36
	tilecoll HOLE, HOLE, FLOOR, FLOOR ; 37
	tilecoll HOLE, FLOOR, HOLE, FLOOR ; 38
	tilecoll HOLE, FLOOR, FLOOR, HOLE ; 39
	tilecoll FLOOR, HOLE, HOLE, FLOOR ; 3a
	tilecoll FLOOR, HOLE, FLOOR, HOLE ; 3b
	tilecoll FLOOR, FLOOR, HOLE, HOLE ; 3c
	tilecoll HOLE, HOLE, HOLE, FLOOR ; 3d
	tilecoll HOLE, HOLE, FLOOR, HOLE ; 3e
	tilecoll HOLE, FLOOR, HOLE, HOLE ; 3f
	tilecoll FLOOR, HOLE, HOLE, HOLE ; 40
	tilecoll HOLE, HOLE, HOLE, HOLE ; 41
	tilecoll HOLE, WALL, HOLE, WALL ; 42
	tilecoll HOLE, HOLE, WALL, WALL ; 43
	tilecoll HOLE, FLOOR, WALL, WALL ; 44
	tilecoll FLOOR, HOLE, WALL, WALL ; 45
	tilecoll HOLE, WALL, FLOOR, WALL ; 46
	tilecoll FLOOR, WALL, HOLE, WALL ; 47
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 48
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 49
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 4a
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 4b
	tilecoll FLOOR, FLOOR, WALL, WALL ; 4c
	tilecoll FLOOR, FLOOR, WALL, WALL ; 4d
	tilecoll FLOOR, FLOOR, WALL, WALL ; 4e
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 4f
	tilecoll WALL, WALL, WALL, WALL ; 50
	tilecoll WALL, WALL, WALL, WALL ; 51
	tilecoll WALL, WALL, WALL, WALL ; 52
	tilecoll HOLE, FLOOR, FLOOR, FLOOR ; 53
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 54
	tilecoll WALL, WALL, WALL, WALL ; 55
	tilecoll FLOOR, FLOOR, WARP_CARPET_DOWN, WARP_CARPET_DOWN ; 56
	tilecoll STAIRCASE, STAIRCASE, STAIRCASE, STAIRCASE ; 57
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 58
	tilecoll WALL, WALL, WALL, WALL ; 59
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 5a
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 5b
