	tilecoll WALL, WALL, WALL, WALL ; 00
	tilecoll WALL, WALL, WALL, WALL ; 01
	tilecoll WALL, WALL, WALL, WALL ; 02
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 03
	tilecoll WALL, FLOOR, WALL, FLOOR ; 04
	tilecoll WALL, WALL, FLOOR, FLOOR ; 05
	tilecoll WALL, TOP_WALL, WALL, WALL ; 06
	tilecoll WALL, WALL, WALL, TOP_WALL ; 07
	tilecoll TOP_WALL, TOP_WALL, WALL, WALL ; 08
	tilecoll TOP_WALL, TOP_WALL, WALL, FLOOR ; 09
	tilecoll FLOOR, FLOOR, MINING, MINING ; 0a
	tilecoll MINING, FLOOR, MINING, MINING ; 0b
	tilecoll FLOOR, MINING, MINING, MINING ; 0c
	tilecoll MINING, WALL, MINING, WALL ; 0d
	tilecoll WALL, WALL, WALL, WALL ; 0e
	tilecoll MINING, MINING, MINING, MINING ; 0f
	tilecoll WALL, WALL, MINING, MINING ; 10
	tilecoll MINING, MINING, MINING, FLOOR ; 11
	tilecoll MINING, MINING, FLOOR, FLOOR ; 12
	tilecoll MINING, MINING, WALL, WALL ; 13
	tilecoll MINING, MINING, WALL, WALL ; 14
	tilecoll MINING, MINING, FLOOR, MINING ; 15
	tilecoll WALL, FLOOR, WALL, FLOOR ; 16
	tilecoll FLOOR, WALL, FLOOR, WALL ; 17
	tilecoll MINING, FLOOR, MINING, FLOOR ; 18
	tilecoll FLOOR, MINING, FLOOR, MINING ; 19
	tilecoll MINING, FLOOR, FLOOR, FLOOR ; 1a
	tilecoll FLOOR, MINING, FLOOR, FLOOR ; 1b
	tilecoll FLOOR, FLOOR, FLOOR, MINING ; 1c
	tilecoll FLOOR, FLOOR, MINING, FLOOR ; 1d
	tilecoll WALL, WALL, WALL, FLOOR ; 1e
	tilecoll WALL, WALL, FLOOR, WALL ; 1f
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 20
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 21
	tilecoll WALL, WALL, DOOR, WALL ; 22
	tilecoll WALL, WALL, WALL, DOOR ; 23
	tilecoll WARP_CARPET_DOWN, WALL, WALL, WALL ; 24
	tilecoll WALL, WARP_CARPET_DOWN, WALL, WALL ; 25
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 26
	tilecoll FLOOR, WALL, WALL, WALL ; 27
	tilecoll WALL, FLOOR, WALL, WALL ; 28
	tilecoll WALL, WALL, FLOOR, WALL ; 29
	tilecoll WALL, WALL, WALL, FLOOR ; 2a
	tilecoll WALL, WALL, WALL, WALL ; 2b
	tilecoll WATER, WATER, WALL, WALL ; 2c
	tilecoll WALL, WALL, WALL, WALL ; 2d
	tilecoll FLOOR, FLOOR, WALL, WALL ; 2e
	tilecoll FLOOR, WALL, WALL, WALL ; 2f
	tilecoll WALL, WALL, WALL, WALL ; 30
	tilecoll FLOOR, FLOOR, WALL, WALL ; 31
	tilecoll FLOOR, WALL, WALL, WALL ; 32
	tilecoll FLOOR, WALL, WALL, WALL ; 33
	tilecoll WALL, WALL, WALL, WALL ; 34
	tilecoll WALL, WALL, WALL, WALL ; 35
	tilecoll FLOOR, WALL, WALL, WALL ; 36
	tilecoll WALL, FLOOR, WALL, WALL ; 37
	tilecoll WALL, FLOOR, WALL, WALL ; 38
	tilecoll WATER, WATER, BUOY, BUOY ; 39
	tilecoll WATER, BUOY, BUOY, BUOY ; 3a
	tilecoll WALL, WALL, WALL, WALL ; 3b
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 3c
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 3d
	tilecoll WALL, WARP_CARPET_DOWN, WALL, WALL ; 3e
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 3f
	tilecoll WALL, WALL, WALL, FLOOR ; 40
	tilecoll WALL, WALL, FLOOR, FLOOR ; 41
	tilecoll WALL, WALL, FLOOR, WALL ; 42
	tilecoll WATER, WATER, WATER, WATER ; 43
	tilecoll WALL, FLOOR, WALL, FLOOR ; 44
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 45
	tilecoll FLOOR, WALL, FLOOR, WALL ; 46
	tilecoll WALL, WALL, WALL, WALL ; 47
	tilecoll FLOOR, WALL, WALL, WALL ; 48
	tilecoll WALL, WALL, WALL, WALL ; 49
	tilecoll WALL, FLOOR, WALL, FLOOR ; 4a
	tilecoll WALL, WALL, WALL, LADDER ; 4b
	tilecoll FLOOR, FLOOR, WALL, WALL ; 4c
	tilecoll FLOOR, FLOOR, WALL, WALL ; 4d
	tilecoll WALL, WALL, WALL, WALL ; 4e
	tilecoll LEDGE_RIGHT, WALL, LEDGE_RIGHT, WALL ; 4f
	tilecoll WALL, WALL, WALL, WALL ; 50
	tilecoll FLOOR, FLOOR, WALL, WALL ; 51
	tilecoll WALL, WALL, WALL, WALL ; 52
	tilecoll WALL, WALL, WALL, WALL ; 53
	tilecoll WALL, WALL, WALL, WALL ; 54
	tilecoll FLOOR, WALL, WALL, WALL ; 55
	tilecoll WALL, FLOOR, WALL, WALL ; 56
	tilecoll WALL, WALL, WALL, WALL ; 57
	tilecoll WALL, WALL, WALL, WALL ; 58
	tilecoll WALL, WALL, WALL, WALL ; 59
	tilecoll WALL, FLOOR, WALL, FLOOR ; 5a
	tilecoll WALL, FLOOR, WALL, FLOOR ; 5b
	tilecoll WALL, WALL, WALL, FLOOR ; 5c
	tilecoll WALL, WALL, FLOOR, FLOOR ; 5d
	tilecoll WALL, WALL, FLOOR, WALL ; 5e
	tilecoll WALL, FLOOR, WALL, DOOR ; 5f
	tilecoll WALL, FLOOR, WALL, WALL ; 60
	tilecoll FLOOR, WALL, WALL, WALL ; 61
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 62
	tilecoll FLOOR, WALL, FLOOR, WALL ; 63
	tilecoll FLOOR, FLOOR, WALL, WALL ; 64
	tilecoll FLOOR, WALL, FLOOR, WALL ; 65
	tilecoll FLOOR, FLOOR, WALL, WALL ; 66
	tilecoll WALL, WALL, WALL, WALL ; 67
	tilecoll FLOOR, WALL, WALL, WALL ; 68
	tilecoll WALL, WALL, WALL, WALL ; 69
	tilecoll WALL, FLOOR, WALL, WALL ; 6a
	tilecoll WALL, FLOOR, WALL, WALL ; 6b
	tilecoll WALL, WALL, WALL, WALL ; 6c
	tilecoll WALL, WALL, WALL, WALL ; 6d
	tilecoll WALL, WALL, WALL, WALL ; 6e
	tilecoll WALL, WALL, WALL, WALL ; 6f
	tilecoll FLOOR, WALL, FLOOR, WALL ; 70
	tilecoll WALL, FLOOR, WALL, FLOOR ; 71
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 72
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 73
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 74
	tilecoll WALL, WALL, FLOOR, FLOOR ; 75
	tilecoll WALL, FLOOR, WALL, WALL ; 76
	tilecoll WALL, FLOOR, WALL, WALL ; 77
	tilecoll WALL, WALL, WALL, WALL ; 78
	tilecoll FLOOR, WALL, FLOOR, WALL ; 79
	tilecoll WALL, FLOOR, WALL, FLOOR ; 7a
	tilecoll FLOOR, WALL, WALL, WALL ; 7b
	tilecoll FLOOR, WALL, WALL, WALL ; 7c
	tilecoll WALL, WALL, WALL, WALL ; 7d
	tilecoll FLOOR, WALL, WALL, WALL ; 7e
	tilecoll WALL, WALL, WALL, WALL ; 7f
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 80
	tilecoll FLOOR, JUMPING_SHOES, WALL, WALL ; 81
	tilecoll JUMPING_SHOES, FLOOR, WALL, WALL ; 82
	tilecoll FLOOR, FLOOR, WALL, WALL ; 83
	tilecoll WALL, WALL, FLOOR, FLOOR ; 84
	tilecoll WALL, WALL, FLOOR, FLOOR ; 85
	tilecoll WALL, WALL, FLOOR, FLOOR ; 86
	tilecoll WALL, WALL, FLOOR, FLOOR ; 87
	tilecoll WALL, WALL, FLOOR, FLOOR ; 88
	tilecoll WALL, WALL, WALL, WALL ; 89
