	tilecoll WALL, WALL, WALL, WALL ; 00
	tilecoll WALL, FLOOR, WALL, FLOOR ; 01
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 02
	tilecoll WALL, FLOOR, WALL, FLOOR ; 03
	tilecoll WALL, FLOOR, WALL, FLOOR ; 04
	tilecoll WALL, FLOOR, WALL, FLOOR ; 05
	tilecoll WALL, FLOOR, WALL, FLOOR ; 06
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 07
	tilecoll WALL, WALL, FLOOR, FLOOR ; 08
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 09
	tilecoll WALL, WALL, FLOOR, FLOOR ; 0a
	tilecoll WALL, WALL, FLOOR, FLOOR ; 0b
	tilecoll WALL, FLOOR, WALL, FLOOR ; 0c
	tilecoll WALL, FLOOR, WALL, FLOOR ; 0d
	tilecoll WALL, FLOOR, WALL, FLOOR ; 0e
	tilecoll FLOOR, FLOOR, WALL, WALL ; 0f
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 10
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 11
	tilecoll WALL, FLOOR, WALL, FLOOR ; 12
	tilecoll WALL, FLOOR, WALL, FLOOR ; 13
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 14
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 15
	tilecoll FLOOR, FLOOR, WALL, WALL ; 16
	tilecoll FLOOR, WALL, WALL, WALL ; 17
	tilecoll FLOOR, FLOOR, WALL, WALL ; 18
	tilecoll FLOOR, FLOOR, WALL, WALL ; 19
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 1a
	tilecoll WALL, WALL, FLOOR, FLOOR ; 1b
	tilecoll WALL, WALL, WALL, FLOOR ; 1c
	tilecoll FLOOR, FLOOR, WALL, WALL ; 1d
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 1e
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 1f
	tilecoll WALL, FLOOR, WALL, WALL ; 20
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 21
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 22
	tilecoll WALL, FLOOR, WALL, FLOOR ; 23
	tilecoll WALL, WALL, FLOOR, FLOOR ; 24
	tilecoll FLOOR, FLOOR, WALL, WALL ; 25
	tilecoll WALL, FLOOR, WALL, FLOOR ; 26
	tilecoll FLOOR, WALL, FLOOR, WALL ; 27
	tilecoll WALL, FLOOR, WALL, WALL ; 28
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 29
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 2a
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 2b
	tilecoll WALL, WALL, WALL, FLOOR ; 2c
	tilecoll WALL, FLOOR, WALL, WALL ; 2d
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 2e
	tilecoll FLOOR, WALL, WALL, WALL ; 2f
	tilecoll FLOOR, FLOOR, WARP_CARPET_DOWN, WARP_CARPET_DOWN ; 30
	tilecoll WALL, WALL, FLOOR, FLOOR ; 31
	tilecoll WALL, WALL, WALL, WALL ; 32
	tilecoll WALL, WALL, WALL, WALL ; 33
	tilecoll WALL, WALL, FLOOR, WALL ; 34
	tilecoll WALL, WALL, WALL, WALL ; 35
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 36
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 37
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 38
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 39
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 3a
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 3b
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 3c
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 3d
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 3e
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 3f
	tilecoll WALL, WALL, FLOOR, FLOOR ; 40
	tilecoll WALL, FLOOR, WALL, WALL ; 41
	tilecoll WALL, WALL, FLOOR, WALL ; 42
	tilecoll WALL, FLOOR, WALL, FLOOR ; 43
	tilecoll WALL, WALL, FLOOR, FLOOR ; 44
	tilecoll WALL, WALL, WALL, FLOOR ; 45
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 46
	tilecoll FLOOR, FLOOR, WALL, WALL ; 47
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 48
	tilecoll WALL, WALL, WALL, WALL ; 49
	tilecoll WALL, WALL, WALL, WALL ; 4a
	tilecoll WALL, WALL, WALL, WALL ; 4b
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 4c
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 4d
