	tilecoll WALL, WALL, WALL, WALL ; 00
	tilecoll WALL, WALL, WALL, WALL ; 01
	tilecoll WALL, WALL, WALL, WALL ; 02
	tilecoll WALL, WALL, WALL, WALL ; 03
	tilecoll WALL, WALL, WALL, WALL ; 04
	tilecoll WALL, WALL, WALL, WALL ; 05
	tilecoll WALL, WALL, WALL, WALL ; 06
	tilecoll WALL, WALL, WALL, WALL ; 07
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 08
	tilecoll FLOOR, WARP_CARPET_RIGHT, FLOOR, WARP_CARPET_RIGHT ; 09
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 0a
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 0b
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 0c
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 0d
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 0e
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 0f
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 10
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 11
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 12
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 13
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 14
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 15
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 16
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 17
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 18
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 19
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 1a
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 1b
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 1c
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 1d
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 1e
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 1f
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 20
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 21
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 22
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 23
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 24
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 25
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 26
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 27
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 28
	tilecoll WALL, FLOOR, WALL, FLOOR ; 29
	tilecoll WALL, WALL, FLOOR, FLOOR ; 2a
	tilecoll FLOOR, WALL, FLOOR, WALL ; 2b
	tilecoll FLOOR, FLOOR, WALL, WALL ; 2c
	tilecoll WALL, WALL, WALL, FLOOR ; 2d
	tilecoll WALL, WALL, FLOOR, WALL ; 2e
	tilecoll FLOOR, WALL, WALL, WALL ; 2f
	tilecoll WALL, FLOOR, WALL, WALL ; 30
	tilecoll WALL, FLOOR, WALL, WALL ; 31
	tilecoll FLOOR, FLOOR, WALL, WALL ; 32
	tilecoll FLOOR, WALL, WALL, WALL ; 33
	tilecoll WALL, FLOOR, WALL, FLOOR ; 34
	tilecoll FLOOR, WALL, FLOOR, WALL ; 35
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 36
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 37
	tilecoll WALL, WALL, WALL, WALL ; 38
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 39
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 3a
	tilecoll WALL, WALL, DOOR, WALL ; 3b
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 3c
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 3d
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 3e
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 3f
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 40
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 41
	tilecoll WALL, WALL, FLOOR, FLOOR ; 42
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 43
	tilecoll , , ,  ; 44
	tilecoll , , ,  ; 45
	tilecoll , , ,  ; 46
