	tilecoll WALL, WALL, WALL, WALL ; 00
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 01
	tilecoll FLOOR, FLOOR, WARP_CARPET_DOWN, FLOOR ; 02
	tilecoll TALL_GRASS, TALL_GRASS, TALL_GRASS, TALL_GRASS ; 03
	tilecoll WALL, WALL, WALL, WALL ; 04
	tilecoll WALL, WALL, WALL, WALL ; 05
	tilecoll WALL, WALL, WALL, WALL ; 06
	tilecoll WALL, WALL, WALL, WALL ; 07
	tilecoll WALL, WALL, WALL, WALL ; 08
	tilecoll WALL, WALL, WALL, WALL ; 09
	tilecoll WALL, WALL, WALL, WALL ; 0a
	tilecoll WALL, WALL, WALL, WALL ; 0b
	tilecoll WARP_CARPET_DOWN, WARP_CARPET_DOWN, WALL, WALL ; 0c
	tilecoll WALL, WALL, WALL, WALL ; 0d
	tilecoll WALL, WALL, WALL, WALL ; 0e
	tilecoll WALL, WALL, WALL, WALL ; 0f
	tilecoll WALL, WALL, WALL, WALL ; 10
	tilecoll WALL, WALL, WALL, WALL ; 11
	tilecoll WALL, WALL, WALL, WALL ; 12
	tilecoll WALL, WALL, WALL, WALL ; 13
	tilecoll MINING, TOP_WALL, MINING, FLOOR ; 14
	tilecoll TOP_WALL, TOP_WALL, FLOOR, FLOOR ; 15
	tilecoll TOP_WALL, MINING, FLOOR, MINING ; 16
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 17
	tilecoll MINING, FLOOR, MINING, FLOOR ; 18
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 19
	tilecoll FLOOR, MINING, FLOOR, MINING ; 1a
	tilecoll MINING, TOP_WALL, MINING, FLOOR ; 1b
	tilecoll MINING, FLOOR, MINING, MINING ; 1c
	tilecoll FLOOR, FLOOR, MINING, MINING ; 1d
	tilecoll FLOOR, MINING, MINING, MINING ; 1e
	tilecoll TOP_WALL, MINING, FLOOR, MINING ; 1f
	tilecoll MINING, TOP_WALL, MINING, FLOOR ; 20
	tilecoll TOP_WALL, TOP_WALL, WARP_CARPET_DOWN, FLOOR ; 21
	tilecoll TOP_WALL, MINING, FLOOR, MINING ; 22
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 23
	tilecoll MINING, FLOOR, MINING, FLOOR ; 24
	tilecoll TOP_WALL, TOP_WALL, TALL_GRASS, TALL_GRASS ; 25
	tilecoll FLOOR, MINING, FLOOR, MINING ; 26
	tilecoll MINING, TOP_WALL, MINING, FLOOR ; 27
	tilecoll MINING, FLOOR, MINING, MINING ; 28
	tilecoll FLOOR, FLOOR, MINING, MINING ; 29
	tilecoll FLOOR, MINING, MINING, MINING ; 2a
	tilecoll TOP_WALL, MINING, FLOOR, MINING ; 2b
	tilecoll WATER, WATER, WATER, WATER ; 2c
	tilecoll WATER, WATER, WATER, WATER ; 2d
	tilecoll WATER, WATER, WATER, WATER ; 2e
	tilecoll WATER, WATER, WATER, WATER ; 2f
	tilecoll WATER, WATER, WATER, WATER ; 30
	tilecoll WATER, WATER, WATER, WATER ; 31
	tilecoll WATER, WATER, WATER, WATER ; 32
	tilecoll WATER, WATER, WATER, WATER ; 33
	tilecoll BUOY, BUOY, BUOY, WATER ; 34
	tilecoll BUOY, BUOY, WATER, WATER ; 35
	tilecoll BUOY, BUOY, WATER, BUOY ; 36
	tilecoll WALL, WALL, MINING, MINING ; 37
	tilecoll BUOY, WATER, BUOY, WATER ; 38
	tilecoll BUOY, BUOY, BUOY, BUOY ; 39
	tilecoll WATER, BUOY, WATER, BUOY ; 3a
	tilecoll WALL, WALL, MINING, MINING ; 3b
	tilecoll BUOY, WATER, BUOY, BUOY ; 3c
	tilecoll WATER, WATER, BUOY, BUOY ; 3d
	tilecoll WATER, BUOY, BUOY, BUOY ; 3e
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 3f
	tilecoll WATER, WATER, WATER, WATER ; 40
	tilecoll WATER, WATER, WATER, WATER ; 41
	tilecoll WATER, WATER, WATER, WATER ; 42
	tilecoll WATER, WATER, WATER, WATER ; 43
	tilecoll WATER, WATER, WATER, WATER ; 44
	tilecoll WATER, WATER, WATER, WATER ; 45
	tilecoll WATER, WATER, WATER, WATER ; 46
	tilecoll WATER, WATER, WATER, WATER ; 47
	tilecoll WATER, WALL, WATER, MINING ; 48
	tilecoll MINING, TOP_WALL, FLOOR, FLOOR ; 49
	tilecoll WALL, WATER, MINING, WATER ; 4a
	tilecoll WALL, WALL, WALL, WALL ; 4b
	tilecoll WATER, MINING, WATER, MINING ; 4c
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 4d
	tilecoll MINING, WATER, MINING, WATER ; 4e
	tilecoll WALL, WALL, WALL, WALL ; 4f
	tilecoll WATER, MINING, WATER, WATER ; 50
	tilecoll MINING, MINING, WATER, WATER ; 51
	tilecoll MINING, WATER, WATER, WATER ; 52
	tilecoll WALL, WALL, WALL, WALL ; 53
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 54
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 55
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 56
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 57
	tilecoll TALL_GRASS, TALL_GRASS, FLOOR, FLOOR ; 58
	tilecoll TALL_GRASS, TALL_GRASS, WALL, TALL_GRASS ; 59
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 5a
	tilecoll WATER, WATER, WATER, WATER ; 5b
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 5c
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 5d
	tilecoll FLOOR, FLOOR, TALL_GRASS, TALL_GRASS ; 5e
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 5f
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 60
	tilecoll FLOOR, WALL, WALL, WALL ; 61
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 62
	tilecoll WALL, WALL, FLOOR, WALL ; 63
	tilecoll FLOOR, TOP_WALL, FLOOR, FLOOR ; 64
	tilecoll TOP_WALL, FLOOR, FLOOR, FLOOR ; 65
	tilecoll FLOOR, TOP_WALL, FLOOR, FLOOR ; 66
	tilecoll TOP_WALL, FLOOR, FLOOR, FLOOR ; 67
	tilecoll TOP_WALL, MINING, WALL, MINING ; 68
	tilecoll WALL, MINING, WALL, MINING ; 69
	tilecoll MINING, MINING, MINING, WATER ; 6a
	tilecoll MINING, WATER, MINING, WATER ; 6b
	tilecoll WALL, MINING, WALL, MINING ; 6c
	tilecoll WALL, MINING, WALL, MINING ; 6d
	tilecoll WATER, WATER, WALL, WATER ; 6e
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 6f
	tilecoll WALL, WALL, WALL, WALL ; 70
	tilecoll WALL, WALL, WALL, WALL ; 71
	tilecoll WALL, WALL, WALL, TOP_WALL ; 72
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 73
	tilecoll WALL, FLOOR, WALL, WALL ; 74
	tilecoll FLOOR, WALL, FLOOR, WALL ; 75
	tilecoll WALL, WATER, TOP_WALL, WALL ; 76
	tilecoll WALL, MINING, WALL, MINING ; 77
	tilecoll FLOOR, WALL, FLOOR, WALL ; 78
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 79
	tilecoll WALL, FLOOR, WALL, FLOOR ; 7a
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 7b
	tilecoll WALL, WALL, WALL, WALL ; 7c
	tilecoll WALL, WALL, WALL, WALL ; 7d
	tilecoll WALL, WALL, WALL, WALL ; 7e
	tilecoll WALL, WALL, WALL, WALL ; 7f
	tilecoll WALL, FLOOR, WALL, FLOOR ; 80
	tilecoll WALL, MINING, WALL, MINING ; 81
	tilecoll WALL, WALL, MINING, MINING ; 82
	tilecoll WALL, MINING, MINING, MINING ; 83
	tilecoll FLOOR, WALL, MINING, MINING ; 84
	tilecoll WALL, MINING, WALL, MINING ; 85
	tilecoll WALL, WALL, WALL, WALL ; 86
	tilecoll WALL, WALL, WALL, WALL ; 87
	tilecoll WALL, WALL, FLOOR, WALL ; 88
	tilecoll WALL, WALL, WALL, WALL ; 89
	tilecoll FLOOR, WALL, WALL, WALL ; 8a
	tilecoll WALL, FLOOR, FLOOR, WALL ; 8b
	tilecoll FLOOR, WALL, WALL, WALL ; 8c
	tilecoll WALL, WALL, WALL, WALL ; 8d
	tilecoll WALL, WALL, WALL, WALL ; 8e
	tilecoll FLOOR, WALL, FLOOR, WALL ; 8f
	tilecoll WALL, WALL, FLOOR, FLOOR ; 90
	tilecoll WALL, WALL, FLOOR, FLOOR ; 91
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 92
	tilecoll WALL, WALL, FLOOR, WALL ; 93
	tilecoll FLOOR, WALL, FLOOR, WALL ; 94
	tilecoll WALL, WALL, FLOOR, FLOOR ; 95
	tilecoll WALL, WALL, MINING, MINING ; 96
	tilecoll WALL, WALL, MINING, MINING ; 97
	tilecoll MINING, WATER, WALL, WALL ; 98
	tilecoll WATER, WATER, WALL, WALL ; 99
	tilecoll WATER, WATER, WALL, WATER ; 9a
	tilecoll WALL, WALL, WALL, WALL ; 9b
	tilecoll WALL, WALL, WALL, WALL ; 9c
	tilecoll WALL, WALL, WALL, WALL ; 9d
	tilecoll WALL, WALL, WALL, WALL ; 9e
	tilecoll WALL, WALL, WALL, WALL ; 9f
	tilecoll WALL, WALL, WALL, WALL ; a0
	tilecoll WALL, WALL, DOOR, WALL ; a1
	tilecoll WALL, WALL, WALL, WALL ; a2
	tilecoll WALL, WALL, WALL, WALL ; a3
	tilecoll WALL, WALL, WALL, DOOR ; a4
	tilecoll WALL, WALL, WALL, WALL ; a5
	tilecoll WALL, WALL, WALL, WALL ; a6
	tilecoll WALL, WALL, WALL, WALL ; a7
	tilecoll WALL, WALL, WALL, WALL ; a8
	tilecoll WALL, WALL, WALL, WALL ; a9
	tilecoll WALL, WALL, WALL, WALL ; aa
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; ab
	tilecoll WALL, WALL, WALL, WALL ; ac
	tilecoll WALL, WALL, WALL, WALL ; ad
	tilecoll WALL, WALL, WALL, WALL ; ae
	tilecoll WALL, WALL, WALL, WALL ; af
	tilecoll WALL, WALL, WALL, WALL ; b0
	tilecoll WALL, WALL, DOOR, POKECENTER_SIGN ; b1
	tilecoll WALL, WALL, WALL, WALL ; b2
	tilecoll WALL, WALL, WALL, DOOR ; b3
	tilecoll WALL, WALL, WALL, WALL ; b4
	tilecoll WALL, WALL, WALL, WALL ; b5
	tilecoll WALL, WALL, WALL, WALL ; b6
	tilecoll WALL, WALL, WALL, WALL ; b7
	tilecoll WALL, WALL, WALL, WALL ; b8
	tilecoll WALL, WALL, WALL, DOOR ; b9
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; ba
	tilecoll WALL, WALL, MART_SIGN, WALL ; bb
	tilecoll WALL, WALL, WALL, WALL ; bc
	tilecoll WALL, WALL, WALL, WALL ; bd
	tilecoll WALL, WALL, WALL, WALL ; be
	tilecoll WALL, WALL, WALL, WALL ; bf
	tilecoll WALL, WALL, WALL, WALL ; c0
	tilecoll WALL, WALL, WALL, WALL ; c1
	tilecoll WALL, WALL, WALL, WALL ; c2
	tilecoll WALL, WALL, WALL, WALL ; c3
	tilecoll WALL, WALL, WALL, WALL ; c4
	tilecoll WALL, WALL, WALL, DOOR ; c5
	tilecoll WALL, WALL, WALL, WALL ; c6
	tilecoll WALL, WALL, WALL, WALL ; c7
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; c8
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; c9
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; ca
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; cb
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; cc
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; cd
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; ce
	tilecoll FLOOR, FLOOR, TALL_GRASS, TALL_GRASS ; cf
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; d0
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; d1
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; d2
	tilecoll FLOOR, FLOOR, TALL_GRASS, TALL_GRASS ; d3
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; d4
	tilecoll TALL_GRASS, TALL_GRASS, WALL, TALL_GRASS ; d5
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; d6
	tilecoll FLOOR, WATER, FLOOR, WATER ; d7
	tilecoll FLOOR, WATER, FLOOR, WATER ; d8
	tilecoll WATER, WATER, FLOOR, WATER ; d9
	tilecoll WATER, WATER, WARP_CARPET_DOWN, FLOOR ; da
	tilecoll MINING, MINING, MINING, FLOOR ; db
	tilecoll TOP_WALL, MINING, FLOOR, MINING ; dc
	tilecoll FLOOR, MINING, MINING, MINING ; dd
	tilecoll WALL, WALL, MINING, MINING ; de
	tilecoll TOP_WALL, MINING, FLOOR, MINING ; df
