	const_def
	const ABILITY_NONE         ; 00
	const ABILITY_TORRENT
	const ABILITY_OVERGROW
	const ABILITY_BLAZE
	const ABILITY_PRESSURE
	const ABILITY_STATIC
	const ABILITY_LEVITATE
	const ABILITY_SOUNDPROOF
	const ABILITY_POISON_POINT ; 08
	const ABILITY_EFFECT_SPORE
	const ABILITY_SWARM
	const ABILITY_SHIELD_DUST
	const ABILITY_LIMBER
	const ABILITY_LIQUID_OOZE
	const ABILITY_GUTS
	const ABILITY_CUTE_CHARM
	const ABILITY_FLAME_BODY   ; 10
	const ABILITY_HYPER_CUTTER
	const ABILITY_INTIMIDATE
	const ABILITY_CLEAR_BODY
	const ABILITY_ARENA_TRAP
	const ABILITY_DROUGHT
	const ABILITY_DRIZZLE
	const ABILITY_SAND_STREAM
	const ABILITY_SNOW_WARNING ; 18
	const ABILITY_SYNCHRONIZE
	const ABILITY_RUN_AWAY
	const ABILITY_MOODY
	const ABILITY_SPEED_BOOST
	const ABILITY_RIVALRY
	const ABILITY_TRACE
	const ABILITY_KLUTZ
	const ABILITY_EARLY_BIRD   ; 20
	const ABILITY_SHED_SKIN
	const ABILITY_STURDY
	const ABILITY_MAGMA_ARMOR
	const ABILITY_STENCH
	const ABILITY_ILLUMINATE
	const ABILITY_NO_GUARD
	const ABILITY_WHITE_SMOKE
	const ABILITY_VITAL_SPIRIT ; 28
	const ABILITY_INSOMNIA
	const ABILITY_SNOW_CLOAK
	const ABILITY_SAND_VEIL
	const ABILITY_LIGHTNINGROD
	const ABILITY_INNER_FOCUS
	const ABILITY_STEADFAST
	const ABILITY_ICE_BODY
	const ABILITY_FLASH_FIRE   ; 30
	const ABILITY_ROCK_HEAD
	const ABILITY_HEATPROOF
	const ABILITY_SNIPER
	const ABILITY_BATTLE_ARMOR
	const ABILITY_MOLD_BREAKER
	const ABILITY_CHLOROPHYLL
	const ABILITY_SWIFT_SWIM
	const ABILITY_UNBURDEN     ; 38
	const ABILITY_AFTERMATH
	const ABILITY_OBLIVIOUS
	const ABILITY_OWN_TEMPO
	const ABILITY_MAGNET_PULL
	const ABILITY_KEEN_EYE
	const ABILITY_STALL
	const ABILITY_FRISK
	const ABILITY_THICK_FAT    ; 40
	const ABILITY_RECKLESS
	const ABILITY_IRON_FIST
	const ABILITY_SOLID_ROCK
	const ABILITY_SERENE_GRACE
	const ABILITY_NATURAL_CURE
	const ABILITY_LEAF_GUARD
	const ABILITY_SCRAPPY
	const ABILITY_WATER_VEIL   ; 48
	const ABILITY_RAIN_DISH
	const ABILITY_TECHNICIAN
	const ABILITY_MOTOR_DRIVE
	const ABILITY_SUPER_LUCK
	const ABILITY_ADAPTABILITY
	const ABILITY_WATER_ABSORB
	const ABILITY_VOLT_ABSORB
	const ABILITY_DOWNLOAD     ; 50
	const ABILITY_SUCTION_CUPS
	const ABILITY_IMMUNITY
	const ABILITY_COMPETITIVE
	const ABILITY_HUSTLE
	const ABILITY_HUGE_POWER
	const ABILITY_SIMPLE
	const ABILITY_POISON_HEAL
	const ABILITY_COMPOUNDEYES ; 58
	const ABILITY_MARVEL_SCALE
	const ABILITY_PICKUP
	const ABILITY_QUICK_FEET
	const ABILITY_AIR_LOCK
	const ABILITY_TINTED_LENS
	const ABILITY_DRY_SKIN
	const ABILITY_TANGLED_FEET
	const ABILITY_CONTRARY     ; 60
	const ABILITY_TRUANT
	const ABILITY_NALJO_FURY
	const ABILITY_SHARPNESS
	const ABILITY_UNKNOWN
