BATTLETOWER_NO_CHALLENGE         EQU 0
BATTLETOWER_SAVED_AND_LEFT       EQU 1
BATTLETOWER_CHALLENGE_IN_PROGESS EQU 2
BATTLETOWER_WON_CHALLENGE        EQU 3
BATTLETOWER_RECEIVED_REWARD      EQU 4

BTMON_STRUCT_LENGTH EQUS "(wBTOTPkmn1StatsEnd - wBTOTPkmn1)"
BTMON_DATA_LENGTH EQU 29
