IF DEF(BUILD_DATE)
ST_DAY   = (BUILD_DATE % 100) - 1
ST_MONTH = ((BUILD_DATE / 100) % 100) - 1
ST_YEAR  = (BUILD_DATE / 10000) - 2000
IF (ST_DAY < 0) || (ST_DAY > 30)
ST_DAY   = 0
ENDC
IF (ST_MONTH < 0) || (ST_MONTH > 11)
ST_MONTH = 0
ENDC
ELSE
ST_DAY   = __UTC_DAY__ - 1
ST_MONTH = __UTC_MONTH__ - 1
ST_YEAR  = __UTC_YEAR__ - 2000
ENDC
IF (ST_YEAR < 0) || (ST_YEAR > 255)
ST_YEAR  = 0
ENDC
