	const_def
	const SCGB_BATTLE_GRAYSCALE
	const SCGB_BATTLE_COLORS
	const SCGB_TOWN_MAP_PALS
	const SCGB_STATS_SCREEN_HP_PALS
	const SCGB_POKEDEX
	const SCGB_SLOT_MACHINE
	const SCGB_SCROLLINGMENU
	const SCGB_MAPPALS
	const SCGB_PARTY_MENU
	const SCGB_EVOLUTION
	const SCGB_MOVE_LIST
	const SCGB_POKEDEX_SEARCH_OPTION
	const SCGB_POKEPIC
	const SCGB_PACKPALS
	const SCGB_TRAINER_CARD
	const SCGB_BILLS_PC
	const SCGB_FOSSIL_PUZZLE
	const SCGB_GAMEFREAK_LOGO
	const SCGB_PLAYER_OR_MON_FRONTPIC_PALS
	const SCGB_TRADE_TUBE
	const SCGB_FRONTPICPALS
	const SCGB_SECOND_LOGO

SCGB_PARTY_MENU_HP_PALS EQU -4
SCGB_RAM EQU -1
