; These are parsed by rgbasm and by bspcomp, so they use a shared syntax.

	define COLL_HIGH_NYBBLE_GRASS,     16 ; $10
	define COLL_HIGH_NYBBLE_WATER,     32 ; $20
	define COLL_HIGH_NYBBLE_WATERFALL, 48 ; $30
	define COLL_HIGH_NYBBLE_CURRENT,   64 ; $40
	define COLL_HIGH_NYBBLE_WALK,      80 ; $50
	define COLL_HIGH_NYBBLE_WARPS,    112 ; $70
	define COLL_HIGH_NYBBLE_LEDGES,   160 ; $a0

	define COLL_FLOOR,                  0 ; $00
	define COLL_WALL,                   7 ; $07
	define COLL_SNOW,                   8 ; $08
	define COLL_CUT_TREE,              18 ; $12
	define COLL_SUPER_TALL_GRASS,      20 ; $14
	define COLL_HEADBUTT_TREE,         21 ; $15
	define COLL_TALL_GRASS,            24 ; $18
	define COLL_ICE,                   35 ; $23
	define COLL_WHIRLPOOL,             36 ; $24
	define COLL_BUOY,                  39 ; $27
	define COLL_WATER,                 41 ; $29
	define COLL_WATERFALL_RIGHT,       48 ; $30
	define COLL_WATERFALL_LEFT,        49 ; $31
	define COLL_WATERFALL_UP,          50 ; $32
	define COLL_WATERFALL,             51 ; $33
	define COLL_CURRENT_STOP,          64 ; $40
	define COLL_CURRENT_RIGHT,         65 ; $41
	define COLL_CURRENT_LEFT,          66 ; $42
	define COLL_CURRENT_UP,            67 ; $43
	define COLL_CURRENT_DOWN,          68 ; $44
	define COLL_BRAKE,                 80 ; $50
	define COLL_WALK_RIGHT,            81 ; $51
	define COLL_WALK_LEFT,             82 ; $52
	define COLL_WALK_UP,               83 ; $53
	define COLL_WALK_DOWN,             84 ; $54
	define COLL_HOLE,                  96 ; $60
	define COLL_WARP_CARPET_DOWN,     112 ; $70
	define COLL_DOOR,                 113 ; $71
	define COLL_LADDER,               114 ; $72
	define COLL_WARP_CARPET_LEFT,     118 ; $76
	define COLL_WARP_CARPET_UP,       120 ; $78
	define COLL_STAIRCASE,            122 ; $7a
	define COLL_CAVE,                 123 ; $7b
	define COLL_WARP_PANEL,           124 ; $7c
	define COLL_WARP_CARPET_RIGHT,    126 ; $7e
	define COLL_COUNTER,              144 ; $90
	define COLL_BOOKSHELF,            145 ; $91
	define COLL_TV,                   146 ; $92
	define COLL_PC,                   147 ; $93
	define COLL_SMELTING,             148 ; $94
	define COLL_TOWN_MAP,             149 ; $95
	define COLL_MART_SHELF,           150 ; $96
	define COLL_JUMPING_SHOES,        151 ; $97
	define COLL_POKECENTER_SIGN,      152 ; $98
	define COLL_MART_SIGN,            153 ; $99
	define COLL_OASIS,                155 ; $9b
	define COLL_MINING,               157 ; $9d
	define COLL_FAST_CURRENT,         159 ; $9f
	define COLL_LEDGE_RIGHT,          160 ; $a0
	define COLL_LEDGE_LEFT,           161 ; $a1
	define COLL_LEDGE_UP,             162 ; $a2
	define COLL_LEDGE_DOWN,           163 ; $a3
	define COLL_LEDGE_DOWN_RIGHT,     164 ; $a4
	define COLL_LEDGE_DOWN_LEFT,      165 ; $a5
	define COLL_LEDGE_UP_RIGHT,       166 ; $a6
	define COLL_LEDGE_UP_LEFT,        167 ; $a7
	define COLL_RIGHT_WALL,           176 ; $b0
	define COLL_LEFT_WALL,            177 ; $b1
	define COLL_TOP_WALL,             178 ; $b2
	define COLL_BOTTOM_WALL,          179 ; $b3
	define COLL_MAGNETIC_TAPE_DRIVE,  180 ; $b4
