	const_def
	const CREDITS_STAFF
	const CREDITS_INITIAL_1
	const CREDITS_INITIAL_2
	const CREDITS_KBM_1
	const CREDITS_KBM_2
	const CREDITS_ORIGINAL_DEVS_1
	const CREDITS_ORIGINAL_DEVS_2
	const CREDITS_LEAKERS_1
	const CREDITS_LEAKERS_2
	const CREDITS_GAME_FREAK_1
	const CREDITS_GAME_FREAK_2
	const CREDITS_GAME_FREAK_3
	const CREDITS_YOU
	const CREDITS_CLOSING

const_value = -7
	const CREDITS_THEEND
	const CREDITS_WAIT2
	const CREDITS_MUSIC
	const CREDITS_CLEAR
	const CREDITS_SCENE
	const CREDITS_WAIT
	const CREDITS_END
