	const_def
	const MART_STANDARD
	const MART_HERB
	const MART_BARGAIN
	const MART_PHARMACIST
	const MART_ROOFTOPSALE
	const MART_BATTLETOWER
	const MART_BATTLEARCADE
	const MART_GOLDTOKEN

	const_def
	const CAPER_STANDARD_MART
	const OXALIS_STANDARD_MART
	const SPURGE_STANDARD_MART_1
	const SPURGE_STANDARD_MART_2
	const SPURGE_STANDARD_MART_3
	const SPURGE_STANDARD_MART_4
	const HEATH_STANDARD_MART
	const LAUREL_STANDARD_MART
	const TORENIA_STANDARD_MART
	const PHACELIA_STANDARD_MART
	const SAXIFRAGE_STANDARD_MART
	const PHLOX_STANDARD_MART
	const ACANIA_STANDARD_MART
	const SAFFRON_STANDARD_MART
	const LEAGUE_STANDARD_MART
	const GRAVEL_STANDARD_MART
	const MERSON_STANDARD_MART
	const OWSAURI_STANDARD_MART
	const MORAGA_STANDARD_MART
	const JAERU_STANDARD_MART
	const HAYWARD_STANDARD_MART_1
	const HAYWARD_STANDARD_MART_2
	const HAYWARD_STANDARD_MART_3
	const HAYWARD_STANDARD_MART_4
	const HAYWARD_STANDARD_MART_5
	const BOTAN_STANDARD_MART
	const CASTRO_STANDARD_MART
	const EAGULOU_STANDARD_MART
	const AZALEA_STANDARD_MART
	const GOLDENROD_STANDARD_MART
	const SOUTHERLY_STANDARD_MART
	const SILPH_WAREHOUSE_STANDARD_MART

HAYWARD_STANDARD_MART_6 EQU SPURGE_STANDARD_MART_1
MORAGA_DINER_MART       EQU SPURGE_STANDARD_MART_3

	const_def
	const SPURGE_GOLD_TOKEN_MART
	const LAUREL_GOLD_TOKEN_MART
	const ACANIA_GOLD_TOKEN_MART
	const JAERU_GOLD_TOKEN_MART
