; sprites
	const_def
	const SPRITE_NONE ; 00
	const SPRITE_P0 ; 01
	const SPRITE_P0_BIKE ; 02
	const SPRITE_GAMEBOY_KID ; 03
	const SPRITE_SILVER ; 04
	const SPRITE_OAK ; 05
	const SPRITE_RED ; 06
	const SPRITE_BLUE ; 07
	const SPRITE_BILL ; 08
	const SPRITE_ELDER ; 09
	const SPRITE_MURA ; 0a
	const SPRITE_KURT ; 0b
	const SPRITE_MOM ; 0c
	const SPRITE_JOE ; 0d
	const SPRITE_BROWNS_MOM ; 0e
	const SPRITE_JEN ; 0f
	const SPRITE_ILK ; 10
	const SPRITE_SORA ; 11
	const SPRITE_JOSIAH ; 12
	const SPRITE_WHITNEY ; 13
	const SPRITE_BUGSY ; 14
	const SPRITE_EDISON ; 15
	const SPRITE_ANDRE ; 16
	const SPRITE_AYAKA ; 17
	const SPRITE_CADENCE ; 18
	const SPRITE_BRUCE ; 19
	const SPRITE_KARPMAN ; 1a
	const SPRITE_YUKI ; 1b
	const SPRITE_DAICHI ; 1c
	const SPRITE_LILY ; 1d
	const SPRITE_LANCE ; 1e
	const SPRITE_SPARKY ; 1f
	const SPRITE_LOIS ; 20
	const SPRITE_KOJI ; 21
	const SPRITE_SABRINA ; 22
	const SPRITE_COOLTRAINER_M ; 23
	const SPRITE_COOLTRAINER_F ; 24
	const SPRITE_BUG_CATCHER ; 25
	const SPRITE_TWIN ; 26
	const SPRITE_YOUNGSTER ; 27
	const SPRITE_LASS ; 28
	const SPRITE_TEACHER ; 29
	const SPRITE_BUENA ; 2a
	const SPRITE_SUPER_NERD ; 2b
	const SPRITE_ROCKER ; 2c
	const SPRITE_POKEFAN_M ; 2d
	const SPRITE_POKEFAN_F ; 2e
	const SPRITE_GRAMPS ; 2f
	const SPRITE_GRANNY ; 30
	const SPRITE_SWIMMER_GUY ; 31
	const SPRITE_SWIMMER_GIRL ; 32
	const SPRITE_BIG_SNORLAX ; 33
	const SPRITE_SURFING_PIKACHU ; 34
	const SPRITE_ROCKET ; 35
	const SPRITE_PALETTE_PATROLLER ; 36
	const SPRITE_NURSE ; 37
	const SPRITE_LINK_RECEPTIONIST ; 38
	const SPRITE_CLERK ; 39
	const SPRITE_FISHER ; 3a
	const SPRITE_FISHING_GURU ; 3b
	const SPRITE_SCIENTIST ; 3c
	const SPRITE_KIMONO_GIRL ; 3d
	const SPRITE_SAGE ; 3e
	const SPRITE_GOLD ; 3f
	const SPRITE_GENTLEMAN ; 40
	const SPRITE_BLACK_BELT ; 41
	const SPRITE_RECEPTIONIST ; 42
	const SPRITE_OFFICER ; 43
	const SPRITE_CAL ; 44
	const SPRITE_SLOWPOKE ; 45
	const SPRITE_CAPTAIN ; 46
	const SPRITE_BIG_LAPRAS ; 47
	const SPRITE_GYM_GUY ; 48
	const SPRITE_SAILOR ; 49
	const SPRITE_BIKER ; 4a
	const SPRITE_BURGLAR ; 4b
	const SPRITE_MONSTER ; 4c
	const SPRITE_FAIRY ; 4d
	const SPRITE_BIRD ; 4e
	const SPRITE_DRAGON ; 4f
	const SPRITE_BIG_ONIX ; 50
	const SPRITE_N64 ; 51
	const SPRITE_SUDOWOODO ; 52
	const SPRITE_SURF ; 53
	const SPRITE_POKE_BALL ; 54
	const SPRITE_POKEDEX ; 55
	const SPRITE_PAPER ; 56
	const SPRITE_VIRTUAL_BOY ; 57
	const SPRITE_OLD_LINK_RECEPTIONIST ; 58
	const SPRITE_ROCK ; 59
	const SPRITE_BOULDER ; 5a
	const SPRITE_SNES ; 5b
	const SPRITE_FAMICOM ; 5c
	const SPRITE_FRUIT_TREE ; 5d
	const SPRITE_GOLD_TROPHY ; 5e
	const SPRITE_SILVER_TROPHY ; 5f
	const SPRITE_P1 ; 60
	const SPRITE_P1_BIKE ; 61
	const SPRITE_KURT_OUTSIDE ; 62
	const SPRITE_SUICUNE ; 63
	const SPRITE_ENTEI ; 64
	const SPRITE_RAIKOU ; 65
	const SPRITE_STANDING_YOUNGSTER ; 66
	const SPRITE_FIRE ;67

	const SPRITE_WALKING_MAGIKARP ;68
	const SPRITE_P0_SURF ;69
	const SPRITE_P1_SURF ;6a
	const SPRITE_P2 ;6b
	const SPRITE_P2_BIKE ;6c
	const SPRITE_P2_SURF ;6d
	const SPRITE_P3 ;6e
	const SPRITE_P3_BIKE ;6f
	const SPRITE_P3_SURF ;70
	const SPRITE_P4 ;71
	const SPRITE_P4_BIKE ;72
	const SPRITE_P4_SURF ;73
	const SPRITE_P5 ;74
	const SPRITE_P5_BIKE ;75
	const SPRITE_P5_SURF ;76
	const SPRITE_P6 ;77
	const SPRITE_P6_BIKE ;78
	const SPRITE_P6_SURF ;79
	const SPRITE_P7 ;7a
	const SPRITE_P7_BIKE ;7b
	const SPRITE_P7_SURF ;7c
	const SPRITE_P8 ;7d
	const SPRITE_P8_BIKE ;7e
	const SPRITE_P8_SURF ;7f
	const SPRITE_P9 ;80
	const SPRITE_P9_BIKE ;81
	const SPRITE_P9_SURF ;82
	const SPRITE_P10 ;83
	const SPRITE_P10_BIKE ;84
	const SPRITE_P10_SURF ;85
	const SPRITE_P11 ;86
	const SPRITE_P11_BIKE ;87
	const SPRITE_P11_SURF ;88
	const SPRITE_BOARDER ;89
	const SPRITE_PSYCHIC ;8A
	const SPRITE_SCHOOLBOY ;8B
	const SPRITE_JUGGLER ;8C
	const SPRITE_BEAUTY ;8D
	const SPRITE_POKEMANIAC ;8E
	const SPRITE_FIREBREATHER ;8F
	const SPRITE_HIKER ;90
	const SPRITE_PICNICKER ;91
	const SPRITE_CAMPER ;92
	const SPRITE_BIRDKEEPER ;93
	const SPRITE_R_BEAUTY ;94
	const SPRITE_R_BIKER ;95
	const SPRITE_R_BIRDKEEPER ;96
	const SPRITE_R_BLACKBELT ;97
	const SPRITE_R_BUGCATCHER ;98
	const SPRITE_R_BURGLAR ;99
	const SPRITE_R_CHANNELER ;9A
	const SPRITE_R_COOLTRAINERF ;9B
	const SPRITE_R_COOLTRAINERM ;9C
	const SPRITE_R_CUEBALL ;9D
	const SPRITE_R_ENGINEER ;9E
	const SPRITE_R_GENTLEMAN ;9F
	const SPRITE_R_FISHER ;A0
	const SPRITE_R_GAMBLER ;A1
	const SPRITE_R_HIKER ;A2
	const SPRITE_R_JRTRAINERF ;A3
	const SPRITE_R_JRTRAINERM ;A4
	const SPRITE_R_JUGGLER ;A5
	const SPRITE_R_LASS ;A6
	const SPRITE_R_MANIAC ;A7
	const SPRITE_R_NERD ;A8
	const SPRITE_R_PSYCHIC ;A9
	const SPRITE_R_ROCKER ;AA
	const SPRITE_R_SAILOR ;AB
	const SPRITE_R_SCIENTIST ;AC
	const SPRITE_R_SWIMMER ;AD
	const SPRITE_R_TAMER ;AE
	const SPRITE_R_YOUNGSTER ;AF
	const SPRITE_MINER ;B0
	const SPRITE_GUITARISTF ;B1
	const SPRITE_DELINQUENTM ;B2
	const SPRITE_DELINQUENTF ;B3
	const SPRITE_CHEERLEADER ;B4
	const SPRITE_SHERYL ;B5
	const SPRITE_BROWN ;B6
	const SPRITE_P12_BIKE ;B7
	const SPRITE_P12_SURF ;B8
	const SPRITE_EGG ;B9
	const SPRITE_POKEONLY_PLAYER ;BA

SPRITE_POKEMON EQU const_value
	const SPRITE_BAGON ; bb
	const SPRITE_CATERPIE ; bc
	const SPRITE_METAPOD ; bd
	const SPRITE_BUTTERFREE ; be
	const SPRITE_WARTORTLE ; bf
	const SPRITE_CHARIZARD ; c0
	const SPRITE_XATU ; c1
	const SPRITE_SURSKIT ; c2
	const SPRITE_TOTODILE ; c3
	const SPRITE_GENGAR ; c4
	const SPRITE_MACHOKE ; c5
	const SPRITE_GROUDON ; c6
	const SPRITE_AGGRON ; c7
	const SPRITE_FAMBACO ; c8
	const SPRITE_ELECTABUZZ ; c9
	const SPRITE_RAICHU ; ca
	const SPRITE_FLAAFFY ; cb
	const SPRITE_BRONZONG ; cc
	const SPRITE_HARIYAMA ; cd
	const SPRITE_METAGROSS ; ce
	const SPRITE_KYOGRE ; cf
	const SPRITE_RHYDON ; d0
	const SPRITE_MOLTRES ; d1
	const SPRITE_TYPHLOSION ; d2
	const SPRITE_FEAROW ; d3
	const SPRITE_PIDGEOT ; d4
	const SPRITE_SWELLOW ; d5
	const SPRITE_ARTICUNO ; d6
	const SPRITE_PHANCERO ; d7
	const SPRITE_HITMONCHAN ; d8
	const SPRITE_GLACEON ; d9
	const SPRITE_BLASTOISE ; da
	const SPRITE_MAGMORTAR ; db
	const SPRITE_AMPHAROS ; dc
	const SPRITE_MILOTIC ; dd
	const SPRITE_LIBABEEL ; de
	const SPRITE_RAIWATO ; df
	const SPRITE_ABRA ; e0
	const SPRITE_PIKACHU ; e1
	const SPRITE_CHARMANDER ; e2
	const SPRITE_LARVITAR ; e3
	const SPRITE_VARANEOUS ; e4
	const SPRITE_RAYQUAZA ; e5
	const SPRITE_MEW ; e6
	const SPRITE_ZAPDOS ; e7

const_value = $ec
	const SPRITE_DAYCARE_MON_1 ; ec
	const SPRITE_DAYCARE_MON_2 ; ed

const_value = $f0
SPRITE_VARS EQU const_value
	const SPRITE_CONSOLE ; f0
	const SPRITE_DOLL_1 ; f1
	const SPRITE_DOLL_2 ; f2
	const SPRITE_BIG_DOLL ; f3
	const SPRITE_WEIRD_TREE ; f4
	const SPRITE_OLIVINE_RIVAL ; f5
	const SPRITE_AZALEA_ROCKET ; f6
	const SPRITE_CASTRO_GYM_1 ; f7
	const SPRITE_CASTRO_GYM_2 ; f8
	const SPRITE_CASTRO_GYM_3 ; f9
	const SPRITE_CASTRO_GYM_4 ; fa
	const SPRITE_COPYCAT ; fb
	const SPRITE_KOJI_IMPERSONATOR ; fc

; sprite types
const_value = 1
	const WALKING_SPRITE
	const STANDING_SPRITE
	const STILL_SPRITE

; sprite header fields
	const_def
	const SPRITEHEADER_ADDR_LO
	const SPRITEHEADER_ADDR_HI
	const SPRITEHEADER_SIZE
	const SPRITEHEADER_BANK
	const SPRITEHEADER_TYPE
	const SPRITEHEADER_PALETTE
NUM_SPRITEHEADER_FIELDS EQU const_value

; sprite palettes
	const_def
	const PAL_OW_PLAYER
	const_def
	const PAL_OW_ORANGE
	const PAL_OW_BLUE
	const PAL_OW_GREEN
	const PAL_OW_BROWN
	const PAL_OW_RED
	const PAL_OW_SILVER
	const PAL_OW_YELLOW
	const PAL_OW_PURPLE

; sprite movement data table indices
	const_def
	const SPRITEMOVEDATA_00                   ; 00
	const SPRITEMOVEDATA_ITEM_TREE            ; 01
	const SPRITEMOVEDATA_WANDER               ; 02
	const SPRITEMOVEDATA_SPINRANDOM_SLOW      ; 03
	const SPRITEMOVEDATA_WALK_UP_DOWN         ; 04
	const SPRITEMOVEDATA_WALK_LEFT_RIGHT      ; 05
	const SPRITEMOVEDATA_STANDING_DOWN        ; 06
	const SPRITEMOVEDATA_STANDING_UP          ; 07
	const SPRITEMOVEDATA_STANDING_LEFT        ; 08
	const SPRITEMOVEDATA_STANDING_RIGHT       ; 09
	const SPRITEMOVEDATA_SPINRANDOM_FAST      ; 0a
	const SPRITEMOVEDATA_PLAYER               ; 0b
	const SPRITEMOVEDATA_0C                   ; 0c
	const SPRITEMOVEDATA_0D                   ; 0d
	const SPRITEMOVEDATA_0E                   ; 0e
	const SPRITEMOVEDATA_0F                   ; 0f
	const SPRITEMOVEDATA_10                   ; 10
	const SPRITEMOVEDATA_11                   ; 11
	const SPRITEMOVEDATA_12                   ; 12
	const SPRITEMOVEDATA_FOLLOWING            ; 13
	const SPRITEMOVEDATA_SCRIPTED             ; 14
	const SPRITEMOVEDATA_SNORLAX              ; 15
	const SPRITEMOVEDATA_POKEMON              ; 16
	const SPRITEMOVEDATA_SUDOWOODO            ; 17
	const SPRITEMOVEDATA_SMASHABLE_ROCK       ; 18
	const SPRITEMOVEDATA_STRENGTH_BOULDER     ; 19
	const SPRITEMOVEDATA_FOLLOWNOTEXACT       ; 1a
	const SPRITEMOVEDATA_SHADOW               ; 1b
	const SPRITEMOVEDATA_EMOTE                ; 1c
	const SPRITEMOVEDATA_SCREENSHAKE          ; 1d
	const SPRITEMOVEDATA_SPINCOUNTERCLOCKWISE ; 1e
	const SPRITEMOVEDATA_SPINCLOCKWISE        ; 1f
	const SPRITEMOVEDATA_BIGDOLLASYM          ; 20
	const SPRITEMOVEDATA_BIGDOLL              ; 21
	const SPRITEMOVEDATA_BOULDERDUST          ; 22
	const SPRITEMOVEDATA_GRASS                ; 23
	const SPRITEMOVEDATA_LAPRAS               ; 24
	const SPRITEMOVEDATA_SNOW                 ; 25
	const SPRITEMOVEDATA_26                   ; 26
	const SPRITEMOVEDATA_ALTERNATE            ; 27
NUM_SPRITEMOVEDATA EQU const_value - 1
SPRITEMOVEDATA_FIELDS EQU 6

; sprite movement functions
	const_def
	const SPRITEMOVEFN_00
	const SPRITEMOVEFN_RANDOM_WALK_Y
	const SPRITEMOVEFN_RANDOM_WALK_X
	const SPRITEMOVEFN_RANDOM_WALK_XY
	const SPRITEMOVEFN_SLOW_RANDOM_SPIN
	const SPRITEMOVEFN_FAST_RANDOM_SPIN
	const SPRITEMOVEFN_STANDING
	const SPRITEMOVEFN_OBEY_DPAD
	const SPRITEMOVEFN_08
	const SPRITEMOVEFN_09
	const SPRITEMOVEFN_0A
	const SPRITEMOVEFN_0B
	const SPRITEMOVEFN_0C
	const SPRITEMOVEFN_0D
	const SPRITEMOVEFN_0E
	const SPRITEMOVEFN_FOLLOW
	const SPRITEMOVEFN_SCRIPTED
	const SPRITEMOVEFN_STRENGTH
	const SPRITEMOVEFN_FOLLOWNOTEXACT
	const SPRITEMOVEFN_SHADOW
	const SPRITEMOVEFN_EMOTE
	const SPRITEMOVEFN_BIG_SNORLAX
	const SPRITEMOVEFN_BOUNCE
	const SPRITEMOVEFN_SCREENSHAKE
	const SPRITEMOVEFN_SPIN_CLOCKWISE
	const SPRITEMOVEFN_SPIN_COUNTERCLOCKWISE
	const SPRITEMOVEFN_BOULDERDUST
	const SPRITEMOVEFN_GRASS
	const SPRITEMOVEFN_SNOW
	const SPRITEMOVEFN_ALTERNATE

	const_def
	const STEP_TYPE_00
	const STEP_TYPE_SLEEP
	const STEP_TYPE_NPC_WALK
	const STEP_TYPE_03
	const STEP_TYPE_04
	const STEP_TYPE_05
	const STEP_TYPE_PLAYER_WALK
	const STEP_TYPE_07
	const STEP_TYPE_NPC_JUMP
	const STEP_TYPE_PLAYER_JUMP
	const STEP_TYPE_HALF_STEP
	const STEP_TYPE_BUMP
	const STEP_TYPE_TELEPORT_FROM
	const STEP_TYPE_TELEPORT_TO
	const STEP_TYPE_SKYFALL
	const STEP_TYPE_0F
	const STEP_TYPE_GOT_BITE
	const STEP_TYPE_ROCK_SMASH
	const STEP_TYPE_RETURN_DIG
	const STEP_TYPE_TRACKING_OBJECT
	const STEP_TYPE_14
	const STEP_TYPE_15
	const STEP_TYPE_16
	const STEP_TYPE_17
	const STEP_TYPE_18
	const STEP_TYPE_SKYFALL_TOP
	const STEP_TYPE_FISHING

	const_def
	const PERSON_ACTION_00
	const PERSON_ACTION_STAND
	const PERSON_ACTION_STEP
	const PERSON_ACTION_BUMP
	const PERSON_ACTION_SPIN
	const PERSON_ACTION_SPIN_FLICKER
	const PERSON_ACTION_FISHING
	const PERSON_ACTION_SHADOW
	const PERSON_ACTION_EMOTE
	const PERSON_ACTION_BIG_SNORLAX
	const PERSON_ACTION_BOUNCE
	const PERSON_ACTION_WEIRD_TREE
	const PERSON_ACTION_BIG_LAPRAS
	const PERSON_ACTION_BIG_DOLL
	const PERSON_ACTION_BOULDER_DUST
	const PERSON_ACTION_GRASS_SHAKE
	const PERSON_ACTION_SKYFALL
	const PERSON_ACTION_RUN
	const PERSON_ACTION_FIELD_MOVE
	const PERSON_ACTION_SNOW
	const PERSON_ACTION_ALTERNATE

	const_def
	const FACING_STEP_DOWN_0
	const FACING_STEP_DOWN_1
	const FACING_STEP_DOWN_2
	const FACING_STEP_DOWN_3
	const FACING_STEP_UP_0
	const FACING_STEP_UP_1
	const FACING_STEP_UP_2
	const FACING_STEP_UP_3
	const FACING_STEP_LEFT_0
	const FACING_STEP_LEFT_1
	const FACING_STEP_LEFT_2
	const FACING_STEP_LEFT_3
	const FACING_STEP_RIGHT_0
	const FACING_STEP_RIGHT_1
	const FACING_STEP_RIGHT_2
	const FACING_STEP_RIGHT_3
	const FACING_FISH_DOWN
	const FACING_FISH_UP
	const FACING_FISH_LEFT
	const FACING_FISH_RIGHT
	const FACING_EMOTE
	const FACING_SHADOW
	const FACING_BIG_DOLL_ASYM
	const FACING_BIG_DOLL_SYM
	const FACING_WEIRD_TREE_0
	const FACING_WEIRD_TREE_1
	const FACING_WEIRD_TREE_2
	const FACING_WEIRD_TREE_3
	const FACING_BOULDER_DUST_1
	const FACING_BOULDER_DUST_2
	const FACING_GRASS_1
	const FACING_GRASS_2
	const FACING_20
	const FACING_21
	const FACING_22
	const FACING_23
	const FACING_SNOW1
	const FACING_SNOW2

	const_def
	const SPRITEANIMSTRUCT_INDEX           ; 0
	const SPRITEANIMSTRUCT_FRAMESET_ID     ; 1
	const SPRITEANIMSTRUCT_ANIM_SEQ_ID     ; 2
	const SPRITEANIMSTRUCT_TILE_ID         ; 3
	const SPRITEANIMSTRUCT_XCOORD          ; 4
	const SPRITEANIMSTRUCT_YCOORD          ; 5
	const SPRITEANIMSTRUCT_XOFFSET         ; 6
	const SPRITEANIMSTRUCT_YOFFSET         ; 7
	const SPRITEANIMSTRUCT_DURATION        ; 8
	const SPRITEANIMSTRUCT_DURATIONOFFSET  ; 9
	const SPRITEANIMSTRUCT_FRAME           ; a
	const SPRITEANIMSTRUCT_JUMPTABLE_INDEX ; b
	const SPRITEANIMSTRUCT_0C              ; c
	const SPRITEANIMSTRUCT_0D              ; d
	const SPRITEANIMSTRUCT_0E              ; e
	const SPRITEANIMSTRUCT_0F              ; f

	const_def
	const SPRITE_ANIM_FRAMESET_00                         ; 00
	const SPRITE_ANIM_FRAMESET_PARTY_MON
	const SPRITE_ANIM_FRAMESET_PARTY_MON_WITH_MAIL
	const SPRITE_ANIM_FRAMESET_PARTY_MON_WITH_ITEM
	const SPRITE_ANIM_FRAMESET_PARTY_MON_FAST
	const SPRITE_ANIM_FRAMESET_PARTY_MON_WITH_MAIL_FAST
	const SPRITE_ANIM_FRAMESET_PARTY_MON_WITH_ITEM_FAST
	const SPRITE_ANIM_FRAMESET_GS_TITLE_TRAIL
	const SPRITE_ANIM_FRAMESET_TEXT_ENTRY_CURSOR          ; 08
	const SPRITE_ANIM_FRAMESET_TEXT_ENTRY_CURSOR_BIG
	const SPRITE_ANIM_FRAMESET_GAMEFREAK_LOGO
	const SPRITE_ANIM_FRAMESET_GS_INTRO_STAR
	const SPRITE_ANIM_FRAMESET_GS_INTRO_SPARKLE
	const SPRITE_ANIM_FRAMESET_SLOT_GOLEM
	const SPRITE_ANIM_FRAMESET_SLOTS_CHANSEY
	const SPRITE_ANIM_FRAMESET_SLOTS_CHANSEY_2
	const SPRITE_ANIM_FRAMESET_SLOTS_EGG                  ; 10
	const SPRITE_ANIM_FRAMESET_WALK_CYCLE
	const SPRITE_ANIM_FRAMESET_STILL_CURSOR
	const SPRITE_ANIM_FRAMESET_TRADE_POKE_BALL
	const SPRITE_ANIM_FRAMESET_TRADE_POKE_BALL_WOBBLE
	const SPRITE_ANIM_FRAMESET_TRADE_POOF
	const SPRITE_ANIM_FRAMESET_TRADE_TUBE_BULGE
	const SPRITE_ANIM_FRAMESET_TRADEMON_ICON
	const SPRITE_ANIM_FRAMESET_TRADEMON_BUBBLE            ; 18
	const SPRITE_ANIM_FRAMESET_EVOLUTION_BALL_OF_LIGHT
	const SPRITE_ANIM_FRAMESET_RADIO_TUNING_KNOB
	const SPRITE_ANIM_FRAMESET_MAGNET_TRAIN_RED
	const skip
	const SPRITE_ANIM_FRAMESET_LEAF
	const SPRITE_ANIM_FRAMESET_CUT_TREE
	const SPRITE_ANIM_FRAMESET_EGG_CRACK
	const SPRITE_ANIM_FRAMESET_EGG_HATCH_1                ; 20
	const SPRITE_ANIM_FRAMESET_EGG_HATCH_2
	const SPRITE_ANIM_FRAMESET_EGG_HATCH_3
	const SPRITE_ANIM_FRAMESET_EGG_HATCH_4
	const SPRITE_ANIM_FRAMESET_GS_INTRO_HO_OH
	const SPRITE_ANIM_FRAMESET_HEADBUTT
	const SPRITE_ANIM_FRAMESET_EZCHAT_CURSOR_1
	const SPRITE_ANIM_FRAMESET_EZCHAT_CURSOR_2
	const SPRITE_ANIM_FRAMESET_EZCHAT_CURSOR_3            ; 28
	const SPRITE_ANIM_FRAMESET_EZCHAT_CURSOR_4
	const SPRITE_ANIM_FRAMESET_EZCHAT_CURSOR_5
	const SPRITE_ANIM_FRAMESET_EZCHAT_CURSOR_6
	const SPRITE_ANIM_FRAMESET_EZCHAT_CURSOR_7
	const SPRITE_ANIM_FRAMESET_BLUE_WALK
	const SPRITE_ANIM_FRAMESET_MAGNET_TRAIN_BLUE
	const SPRITE_ANIM_FRAMESET_MOBILE_TRADE_SENT_BALL
	const SPRITE_ANIM_FRAMESET_MOBILE_TRADE_OT_BALL       ; 30
	const SPRITE_ANIM_FRAMESET_MOBILE_TRADE_CABLE_BULGE
	const SPRITE_ANIM_FRAMESET_MOBILE_TRADE_SENT_PULSE
	const SPRITE_ANIM_FRAMESET_MOBILE_TRADE_OT_PULSE
	const SPRITE_ANIM_FRAMESET_MOBILE_TRADE_PING
	const SPRITE_ANIM_FRAMESET_INTRO_SUICUNE_1
	const SPRITE_ANIM_FRAMESET_INTRO_SUICUNE_2
	const SPRITE_ANIM_FRAMESET_INTRO_PICHU
	const SPRITE_ANIM_FRAMESET_INTRO_WOOPER               ; 38
	const SPRITE_ANIM_FRAMESET_INTRO_UNOWN_1
	const SPRITE_ANIM_FRAMESET_INTRO_UNOWN_2
	const SPRITE_ANIM_FRAMESET_INTRO_UNOWN_3
	const SPRITE_ANIM_FRAMESET_INTRO_UNOWN_4
	const SPRITE_ANIM_FRAMESET_INTRO_UNOWN_F_1
	const SPRITE_ANIM_FRAMESET_INTRO_SUICUNE_AWAY
	const SPRITE_ANIM_FRAMESET_INTRO_UNOWN_F_2
	const SPRITE_ANIM_FRAMESET_CELEBI_LEFT                ; 40
	const SPRITE_ANIM_FRAMESET_CELEBI_RIGHT
	const SPRITE_ANIM_FRAMESET_CUSTOMIZATION_PLAYER
	const SPRITE_ANIM_FRAMESET_PAL02_WALK
	const SPRITE_ANIM_FRAMESET_PAL03_WALK
	const SPRITE_ANIM_FRAMESET_PAL04_WALK
	const SPRITE_ANIM_FRAMESET_PAL05_WALK
	const SPRITE_ANIM_FRAMESET_PAL06_WALK
	const SPRITE_ANIM_FRAMESET_PAL07_WALK                 ; 48
	const SPRITE_ANIM_FRAMESET_SLIDER_CURSOR
	const SPRITE_ANIM_FRAMESET_CALENDAR_CURSOR

	const_def
	const SPRITE_ANIM_SEQ_NULL                            ; 00
	const SPRITE_ANIM_SEQ_PARTY_MON
	const SPRITE_ANIM_SEQ_PARTY_MON_SWITCH
	const SPRITE_ANIM_SEQ_PARTY_MON_SELECTED
	const SPRITE_ANIM_SEQ_GS_TITLE_TRAIL
	const SPRITE_ANIM_SEQ_NAMING_SCREEN_CURSOR
	const SPRITE_ANIM_SEQ_GAMEFREAK_LOGO
	const SPRITE_ANIM_SEQ_GS_INTRO_STAR
	const SPRITE_ANIM_SEQ_GS_INTRO_SPARKLE                ; 08
	const SPRITE_ANIM_SEQ_SLOT_GOLEM
	const SPRITE_ANIM_SEQ_SLOTS_CHANSEY
	const SPRITE_ANIM_SEQ_SLOTS_EGG
	const SPRITE_ANIM_SEQ_0D ;unknown cursor, actually $0C in Prism
	const SPRITE_ANIM_SEQ_MEMORY_GAME_CURSOR
	const SPRITE_ANIM_SEQ_POKEGEAR_ARROW
	const SPRITE_ANIM_SEQ_TRADE_POKE_BALL
	const SPRITE_ANIM_SEQ_TRADE_TUBE_BULGE                ; 10
	const SPRITE_ANIM_SEQ_TRADEMON_IN_TUBE
	const SPRITE_ANIM_SEQ_REVEAL_NEW_MON
	const SPRITE_ANIM_SEQ_RADIO_TUNING_KNOB
	const SPRITE_ANIM_SEQ_CUT_LEAVES
	const SPRITE_ANIM_SEQ_FLY_FROM
	const SPRITE_ANIM_SEQ_FLY_LEAF
	const SPRITE_ANIM_SEQ_FLY_TO
	const SPRITE_ANIM_SEQ_GS_INTRO_HO_OH                  ; 18
	const SPRITE_ANIM_SEQ_EZCHAT_CURSOR
	const SPRITE_ANIM_SEQ_MOBILE_TRADE_SENT_PULSE
	const SPRITE_ANIM_SEQ_MOBILE_TRADE_OT_PULSE
	const SPRITE_ANIM_SEQ_INTRO_SUICUNE
	const SPRITE_ANIM_SEQ_INTRO_PICHU_WOOPER
	const SPRITE_ANIM_SEQ_CELEBI
	const SPRITE_ANIM_SEQ_INTRO_UNOWN
	const SPRITE_ANIM_SEQ_INTRO_UNOWN_F                   ; 20
	const SPRITE_ANIM_SEQ_INTRO_SUICUNE_AWAY
	const SPRITE_ANIM_SEQ_SLIDER_CURSOR
	const SPRITE_ANIM_SEQ_CALENDAR_CURSOR

	const_def
	const SPRITE_ANIM_INDEX_PARTY_MON                     ; 00
	const SPRITE_ANIM_INDEX_GS_TITLE_TRAIL
	const SPRITE_ANIM_INDEX_NAMING_SCREEN_CURSOR
	const SPRITE_ANIM_INDEX_GAMEFREAK_LOGO
	const SPRITE_ANIM_INDEX_GS_INTRO_STAR
	const SPRITE_ANIM_INDEX_GS_INTRO_SPARKLE
	const SPRITE_ANIM_INDEX_SLOT_GOLEM
	const SPRITE_ANIM_INDEX_SLOTS_CHANSEY
	const SPRITE_ANIM_INDEX_SLOTS_EGG                     ; 08
	const SPRITE_ANIM_INDEX_RED_WALK
	const skip
	const SPRITE_ANIM_INDEX_COMPOSE_MAIL_CURSOR
	const SPRITE_ANIM_INDEX_POKEGEAR_ARROW
	const SPRITE_ANIM_INDEX_TRADE_POKE_BALL
	const SPRITE_ANIM_INDEX_TRADE_POOF
	const SPRITE_ANIM_INDEX_TRADE_TUBE_BULGE
	const SPRITE_ANIM_INDEX_TRADEMON_ICON                 ; 10
	const SPRITE_ANIM_INDEX_TRADEMON_BUBBLE
	const SPRITE_ANIM_INDEX_EVOLUTION_BALL_OF_LIGHT
	const skip
	const SPRITE_ANIM_INDEX_MAGNET_TRAIN_RED
	const SPRITE_ANIM_INDEX_LEAF
	const SPRITE_ANIM_INDEX_CUT_TREE
	const SPRITE_ANIM_INDEX_FLY_LEAF
	const SPRITE_ANIM_INDEX_EGG_CRACK                     ; 18
	const skip
	const SPRITE_ANIM_INDEX_HEADBUTT
	const SPRITE_ANIM_INDEX_EGG_HATCH
	const skip
	const SPRITE_ANIM_INDEX_BLUE_WALK
	const SPRITE_ANIM_INDEX_MAGNET_TRAIN_BLUE
	rept 13
		const skip
	endr
	const SPRITE_ANIM_INDEX_PLAYER_CUSTOMIZATION          ; 2C
	const SPRITE_ANIM_INDEX_WALK_02
	const SPRITE_ANIM_INDEX_WALK_03
	const SPRITE_ANIM_INDEX_WALK_04
	const SPRITE_ANIM_INDEX_WALK_05                       ; 30
	const SPRITE_ANIM_INDEX_WALK_06
	const SPRITE_ANIM_INDEX_WALK_07
	const SPRITE_ANIM_INDEX_SLIDER_CURSOR
	const SPRITE_ANIM_INDEX_CALENDAR_CURSOR
	const SPRITE_ANIM_INDEX_NONE

	const_def
	const SPRITE_ANIM_FRAME_IDX_00
	const SPRITE_ANIM_FRAME_IDX_01
	const SPRITE_ANIM_FRAME_IDX_02
	const SPRITE_ANIM_FRAME_IDX_03
	const SPRITE_ANIM_FRAME_IDX_04
	const SPRITE_ANIM_FRAME_IDX_05
	const SPRITE_ANIM_FRAME_IDX_06
	const SPRITE_ANIM_FRAME_IDX_07
	const SPRITE_ANIM_FRAME_IDX_08
	const SPRITE_ANIM_FRAME_IDX_09
	const SPRITE_ANIM_FRAME_IDX_0A
	const SPRITE_ANIM_FRAME_IDX_0B
	const SPRITE_ANIM_FRAME_IDX_0C
	const SPRITE_ANIM_FRAME_IDX_0D
	const SPRITE_ANIM_FRAME_IDX_0E
	const SPRITE_ANIM_FRAME_IDX_0F
	const SPRITE_ANIM_FRAME_IDX_10
	const SPRITE_ANIM_FRAME_IDX_11
	const SPRITE_ANIM_FRAME_IDX_12
	const SPRITE_ANIM_FRAME_IDX_13
	const SPRITE_ANIM_FRAME_IDX_14
	const SPRITE_ANIM_FRAME_IDX_15
	const SPRITE_ANIM_FRAME_IDX_16
	const SPRITE_ANIM_FRAME_IDX_17
	const SPRITE_ANIM_FRAME_IDX_18
	const SPRITE_ANIM_FRAME_IDX_19
	const SPRITE_ANIM_FRAME_IDX_1A
	const SPRITE_ANIM_FRAME_IDX_1B
	const SPRITE_ANIM_FRAME_IDX_1C
	const SPRITE_ANIM_FRAME_IDX_1D
	const SPRITE_ANIM_FRAME_IDX_1E
	const SPRITE_ANIM_FRAME_IDX_1F
	const SPRITE_ANIM_FRAME_IDX_20
	const SPRITE_ANIM_FRAME_IDX_21
	const SPRITE_ANIM_FRAME_IDX_22
	const SPRITE_ANIM_FRAME_IDX_23
	const SPRITE_ANIM_FRAME_IDX_24
	const SPRITE_ANIM_FRAME_IDX_25
	const SPRITE_ANIM_FRAME_IDX_26
	const SPRITE_ANIM_FRAME_IDX_27
	const SPRITE_ANIM_FRAME_IDX_28
	const SPRITE_ANIM_FRAME_IDX_29
	const SPRITE_ANIM_FRAME_IDX_2A
	const SPRITE_ANIM_FRAME_IDX_2B
	const SPRITE_ANIM_FRAME_IDX_2C
	const SPRITE_ANIM_FRAME_IDX_2D
	const SPRITE_ANIM_FRAME_IDX_2E
	const SPRITE_ANIM_FRAME_IDX_2F
	const SPRITE_ANIM_FRAME_IDX_30
	const SPRITE_ANIM_FRAME_IDX_31
	const SPRITE_ANIM_FRAME_IDX_32
	const SPRITE_ANIM_FRAME_IDX_33
	const SPRITE_ANIM_FRAME_IDX_34
	const SPRITE_ANIM_FRAME_IDX_35
	const SPRITE_ANIM_FRAME_IDX_36
	const SPRITE_ANIM_FRAME_IDX_37
	const SPRITE_ANIM_FRAME_IDX_38
	const SPRITE_ANIM_FRAME_IDX_39
	const SPRITE_ANIM_FRAME_IDX_3A
	const SPRITE_ANIM_FRAME_IDX_3B
	const SPRITE_ANIM_FRAME_IDX_3C
	const SPRITE_ANIM_FRAME_IDX_3D
	const SPRITE_ANIM_FRAME_IDX_3E
	const SPRITE_ANIM_FRAME_IDX_3F
	const SPRITE_ANIM_FRAME_IDX_40
	const SPRITE_ANIM_FRAME_IDX_41
	const SPRITE_ANIM_FRAME_IDX_42
	const SPRITE_ANIM_FRAME_IDX_43
	const SPRITE_ANIM_FRAME_IDX_44
	const SPRITE_ANIM_FRAME_IDX_45
	const SPRITE_ANIM_FRAME_IDX_46
	const SPRITE_ANIM_FRAME_IDX_47
	const SPRITE_ANIM_FRAME_IDX_48
	const SPRITE_ANIM_FRAME_IDX_49
	const SPRITE_ANIM_FRAME_IDX_4A
	const SPRITE_ANIM_FRAME_IDX_4B
	const SPRITE_ANIM_FRAME_IDX_4C
	const SPRITE_ANIM_FRAME_IDX_4D
	const SPRITE_ANIM_FRAME_IDX_4E
	const SPRITE_ANIM_FRAME_IDX_4F
	const SPRITE_ANIM_FRAME_IDX_50
	const SPRITE_ANIM_FRAME_IDX_51
	const SPRITE_ANIM_FRAME_IDX_52
	const SPRITE_ANIM_FRAME_IDX_53
	const SPRITE_ANIM_FRAME_IDX_54
	const SPRITE_ANIM_FRAME_IDX_55
	const SPRITE_ANIM_FRAME_IDX_56
	const SPRITE_ANIM_FRAME_IDX_57
	const SPRITE_ANIM_FRAME_IDX_58
	const SPRITE_ANIM_FRAME_IDX_59
	const SPRITE_ANIM_FRAME_IDX_5A
	const SPRITE_ANIM_FRAME_IDX_5B
	const SPRITE_ANIM_FRAME_IDX_5C
	const SPRITE_ANIM_FRAME_IDX_5D
	const SPRITE_ANIM_FRAME_IDX_5E
	const SPRITE_ANIM_FRAME_IDX_5F
	const SPRITE_ANIM_FRAME_IDX_60
	const SPRITE_ANIM_FRAME_IDX_61
	const SPRITE_ANIM_FRAME_IDX_62
	const SPRITE_ANIM_FRAME_IDX_63
	const SPRITE_ANIM_FRAME_IDX_64
	const SPRITE_ANIM_FRAME_IDX_65
	const SPRITE_ANIM_FRAME_IDX_66
	const SPRITE_ANIM_FRAME_IDX_67
	const SPRITE_ANIM_FRAME_IDX_68
	const SPRITE_ANIM_FRAME_IDX_69
	const SPRITE_ANIM_FRAME_IDX_6A
	const SPRITE_ANIM_FRAME_IDX_6B
	const SPRITE_ANIM_FRAME_IDX_6C
	const SPRITE_ANIM_FRAME_IDX_6D
	const SPRITE_ANIM_FRAME_IDX_6E
	const SPRITE_ANIM_FRAME_IDX_6F
	const SPRITE_ANIM_FRAME_IDX_70
	const SPRITE_ANIM_FRAME_IDX_71
	const SPRITE_ANIM_FRAME_IDX_72
	const SPRITE_ANIM_FRAME_IDX_73
	const SPRITE_ANIM_FRAME_IDX_74
	const SPRITE_ANIM_FRAME_IDX_75
	const SPRITE_ANIM_FRAME_IDX_76
	const SPRITE_ANIM_FRAME_IDX_77
	const SPRITE_ANIM_FRAME_IDX_78
	const SPRITE_ANIM_FRAME_IDX_79
	const SPRITE_ANIM_FRAME_IDX_7A
	const SPRITE_ANIM_FRAME_IDX_7B
	const SPRITE_ANIM_FRAME_IDX_7C
	const SPRITE_ANIM_FRAME_IDX_7D
	const SPRITE_ANIM_FRAME_IDX_7E
	const SPRITE_ANIM_FRAME_IDX_7F
	const SPRITE_ANIM_FRAME_IDX_80
	const SPRITE_ANIM_FRAME_IDX_81
	const SPRITE_ANIM_FRAME_IDX_82
	const SPRITE_ANIM_FRAME_IDX_83
	const SPRITE_ANIM_FRAME_IDX_84
	const SPRITE_ANIM_FRAME_IDX_85
	const SPRITE_ANIM_FRAME_IDX_86
	const SPRITE_ANIM_FRAME_IDX_87
	const SPRITE_ANIM_FRAME_IDX_88
	const SPRITE_ANIM_FRAME_IDX_89
	const SPRITE_ANIM_FRAME_IDX_8A
	const SPRITE_ANIM_FRAME_IDX_8B
	const SPRITE_ANIM_FRAME_IDX_8C
	const SPRITE_ANIM_FRAME_IDX_8D
	const SPRITE_ANIM_FRAME_IDX_8E
	const SPRITE_ANIM_FRAME_IDX_8F
	const SPRITE_ANIM_FRAME_IDX_90
	const SPRITE_ANIM_FRAME_IDX_91
	const SPRITE_ANIM_FRAME_IDX_92
	const SPRITE_ANIM_FRAME_IDX_93
	const SPRITE_ANIM_FRAME_IDX_94
	const SPRITE_ANIM_FRAME_IDX_95
	const SPRITE_ANIM_FRAME_IDX_96
	const SPRITE_ANIM_FRAME_IDX_97
	const SPRITE_ANIM_FRAME_IDX_98
	const SPRITE_ANIM_FRAME_IDX_99
	const SPRITE_ANIM_FRAME_IDX_9A
	const SPRITE_ANIM_FRAME_IDX_9B

OBJECT_DISABLE_STEP_TYPE EQU 5
OBJECT_PRIORITY_HIGH EQU 1
OBJECT_PRIORITY_LOW EQU 0
