; wMonType:
PARTYMON   EQU 0
OTPARTYMON EQU 1
BOXMON     EQU 2
BREEDMON   EQU 3
WILDMON    EQU 4

; wOptions:
FAST_TEXT      EQU 0
MED_TEXT       EQU 1
SLOW_TEXT      EQU 2
; bits
TURNING_SPEED  EQU 3
NO_TEXT_SCROLL EQU 4
STEREO         EQU 5
BATTLE_SHIFT   EQU 6
BATTLE_SCENE   EQU 7

; wOptions2:
MENU_ACCOUNT EQU 0

; wGBPrinter:
PRINT_LIGHTEST EQU $00
PRINT_LIGHTER  EQU $20
PRINT_NORMAL   EQU $40
PRINT_DARKER   EQU $60
PRINT_DARKEST  EQU $7f

; wWalkingDirection:
STANDING EQU -1
DOWN     EQU 0
UP       EQU 1
LEFT     EQU 2
RIGHT    EQU 3

; wFacingDirection:
FACE_CURRENT EQU 0
FACE_DOWN  EQU 8
FACE_UP    EQU 4
FACE_LEFT  EQU 2
FACE_RIGHT EQU 1

; wTimeOfDay:
MORN     EQU 0
DAY      EQU 1
NITE     EQU 2
DARKNESS EQU 3

; wScriptFlags:
SCRIPT_RUNNING EQU 2

; wScriptMode:
SCRIPT_OFF EQU 0
SCRIPT_READ EQU 1
SCRIPT_WAIT_MOVEMENT EQU 2
SCRIPT_WAIT EQU 3

; wCurDay:
SUNDAY    EQU 0
MONDAY    EQU 1
TUESDAY   EQU 2
WEDNESDAY EQU 3
THURSDAY  EQU 4
FRIDAY    EQU 5
SATURDAY  EQU 6

; wMapObjects:
NUM_OBJECTS   EQU 16

; InputType:
AUTO_INPUT EQU $ff

; wWhichRegisteredItem:
REGISTERED_POCKET EQU %11000000
REGISTERED_NUMBER EQU %00111111

; wPlayerState:
PLAYER_NORMAL    EQU 0
PLAYER_BIKE      EQU 1
PLAYER_SLIP      EQU 2
PLAYER_SURF      EQU 4
PLAYER_SURF_PIKA EQU 8

OBJECT_STRUCT_LENGTH EQU 40
NUM_OBJECT_STRUCTS EQU 13

; After-Champion Spawn
SPAWN_LANCE EQU 1
SPAWN_RED EQU 2

; wPokemonWithdrawDepositParameter
PC_WITHDRAW EQU 0
PC_DEPOSIT EQU 1
DAYCARE_WITHDRAW EQU 2
DAYCARE_DEPOSIT EQU 3

TREASURE_BAG_CAPACITY EQU 10

	const_def
	const BGMODE_NORMAL
	const BGMODE_TILES_ADDR    ; copy wTileMap to [hBGMapAddress]
	const BGMODE_ATTR_ADDR     ; copy wAttrMap to [hBGMapAddress]
	const BGMODE_TILES_BGMAP1  ; copy wTileMap to vBGMap1
	const BGMODE_ATTR_BGMAP1   ; copy wAttrMap to vBGMap1
	const BGMODE_SOURCE_BGMAP0 ; copy current half of wTileMap to vBGMap0
	const BGMODE_SOURCE_BGMAP1 ; copy current half of wTileMap to vBGMap1
