	add_name "Master Ball"
	add_name "Ultra Ball"
	add_name "BrightPowder"
	add_name "Great Ball"
	add_name "# Ball"
	add_name "Coal"
	add_name "Bicycle"
	add_name "Moon Stone" ;8
	add_name "Antidote"
	add_name "Burn Heal"
	add_name "Ice Heal"
	add_name "Awakening"
	add_name "ParalyzeHeal"
	add_name "Full Restore"
	add_name "Max Potion"
	add_name "Hyper Potion" ;10
	add_name "Super Potion"
	add_name "Potion"
	add_name "Escape Rope"
	add_name "Repel"
	add_name "Max Elixir"
	add_name "Fire Stone"
	add_name "ThunderStone"
	add_name "Water Stone" ;18
	add_name "Poison Guard"
	add_name "HP Up"
	add_name "Protein"
	add_name "Iron"
	add_name "Carbos"
	add_name "Lucky Punch"
	add_name "Calcium"
	add_name "Rare Candy" ;20
	add_name "X Accuracy"
	add_name "Leaf Stone"
	add_name "Metal Powder"
	add_name "Nugget"
	add_name "# Doll"
	add_name "Full Heal"
	add_name "Revive"
	add_name "Max Revive" ;28
	add_name "Guard Spec."
	add_name "Super Repel"
	add_name "Max Repel"
	add_name "Dire Hit"
	add_name "Burn Guard"
	add_name "Fresh Water"
	add_name "Soda Pop"
	add_name "Lemonade" ;30
	add_name "X Attack"
	add_name "Freeze Guard"
	add_name "X Defense"
	add_name "X Speed"
	add_name "X Sp. Atk"
	add_name "Coin Case"
	add_name "Item Finder"
	add_name "Heart Scale"
	add_name "Exp. Share"
	add_name "Old Rod"
	add_name "Good Rod"
	add_name "Silver Leaf"
	add_name "Super Rod"
	add_name "PP Up"
	add_name "Ether"
	add_name "Max Ether" ;40
	add_name "Elixir"
	add_name "Cage Card 1"
	add_name "Rijon Pass"
	add_name "Ferry Ticket"
	add_name "Cage Card 2"
	add_name "Cage Card 3"
	add_name "Cage Card 4"
	add_name "Moomoo Milk" ;48
	add_name "Quick Claw"
	add_name "Pecha Berry"
	add_name "Gold Leaf"
	add_name "Soft Sand"
	add_name "Sharp Beak"
	add_name "Cheri Berry"
	add_name "Aspear Berry"
	add_name "Rawst Berry" ;50
	add_name "Poison Barb"
	add_name "King's Rock"
	add_name "Persim Berry"
	add_name "Chesto Berry"
	add_name "Red Apricorn"
	add_name "TinyMushroom"
	add_name "Big Mushroom"
	add_name "SilverPowder" ;58
	add_name "Blu Apricorn"
	add_name "Sleep Guard"
	add_name "Amulet Coin"
	add_name "Ylw Apricorn"
	add_name "Grn Apricorn"
	add_name "Cleanse Tag"
	add_name "Mystic Water"
	add_name "TwistedSpoon" ;60
	add_name "Wht Apricorn"
	add_name "Blackbelt"
	add_name "Blk Apricorn"
	add_name "Prz Guard"
	add_name "Pnk Apricorn"
	add_name "BlackGlasses"
	add_name "SlowpokeTail"
	add_name "Pink Bow" ;68
	add_name "Stick"
	add_name "Smoke Ball"
	add_name "NeverMeltIce"
	add_name "Magnet"
	add_name "Lum Berry"
	add_name "Pearl"
	add_name "Big Pearl"
	add_name "Everstone" ;70
	add_name "Spell Tag"
	add_name "Silver Egg"
	add_name "Crystal Egg"
	add_name "Ruby Egg"
	add_name "Miracle Seed"
	add_name "Gold Egg"
	add_name "Focus Band"
	add_name "ConfuseGuard" ;78
	add_name "EnergyPowder"
	add_name "Energy Root"
	add_name "Heal Powder"
	add_name "Revival Herb"
	add_name "Hard Stone"
	add_name "Lucky Egg"
	add_name "Emerald Egg"
	add_name "Prism Key" ;80
	add_name "Red Orb"
	add_name "Green Orb"
	add_name "Stardust"
	add_name "Star Piece"
	add_name "Mansion Key"
	add_name "Blue Orb"
	add_name "Sapphire Egg"
	add_name "Curo Shard" ;88
	add_name "Bedroom Key"
	add_name "Charcoal"
	add_name "Berry Juice"
	add_name "Scope Lens"
	add_name "Megaphone"
	add_name "Cigarette"
	add_name "Metal Coat"
	add_name "Dragon Fang" ;90
	add_name "Cage Card 5"
	add_name "Leftovers"
	add_name "Cage Card 6"
	add_name "Eagulou Ball"
	add_name "Giant Rock"
	add_name "Leppa Berry"
	add_name "Dragon Scale"
	add_name "Berserk Gene" ;98
	add_name "Blue Flute"
	add_name "X Sp. Def"
	add_name "Cage Key"
	add_name "Sacred Ash"
	add_name "Reaper Cloth"
	add_name "Gold Token"
	add_name "Ore Case"
	add_name "Dive Ball"
	add_name "Fast Ball"
	add_name "Smelter"
	add_name "Light Ball"
	add_name "Friend Ball"
	add_name "Eviolite"
	add_name "Macho Brace"
	add_name "Burnt Berry"
	add_name "Hyper Share"
	add_name "Sun Stone"
	add_name "Silk Scarf"
	add_name "Dynamite"
	add_name "Upgrade"
	add_name "Oran Berry"
	add_name "Sitrus Berry"
	add_name "Dawn Stone"
	add_name "Gold Dust" ;b0
	add_name "Park Ball"
	add_name "Iron Pickaxe"
	add_name "Shiny Stone"
	add_name "Brick Piece"
	add_name "Red Flute"
	add_name "Yellow Flute"
	add_name "Black Flute"
	add_name "White Flute" ;b8
	add_name "Green Flute"
	add_name "Orange Flute"
	add_name "Soot Sack"
	add_name "Purple Flute"
	add_name "Shop Ticket"
	add_name "Mining Pick"
	add_name "TM Case"
	add_name "Safe Goggles" ;c0
	add_name "Red Jewel"
	add_name "Blue Jewel"
	add_name "Brown Jewel"
	add_name "White Jewel"
	add_name "Prism Jewel"
	add_name "Big Nugget"
	add_name "Heat Rock"
	add_name "Damp Rock" ;c8
	add_name "Smooth Rock"
	add_name "Icy Rock"
	add_name "Light Clay"
	add_name "Shell Bell"
	add_name "Keg of Beer"
	add_name "Fire Ring"
	add_name "Grass Ring"
	add_name "Water Ring" ;d0
	add_name "Thunder Ring"
	add_name "Shiny Ring"
	add_name "Dawn Ring"
	add_name "Dusk Ring"
	add_name "Moon Ring"
	add_name "Dusk Stone"
	add_name "Expert Belt"
	add_name "Trade Stone" ;d8
	add_name "Shiny Ball"
	add_name "Ore"
	add_name "Burger"
	add_name "Muscle Band"
	add_name "Fries"
	add_name "Fossil Case"
	add_name "Silk"
	add_name "Magmarizer" ;e0
	add_name "Electirizer"
	add_name "Prism Scale"
	add_name "Dubious Disc"
	add_name "Razor Claw"
	add_name "Razor Fang"
	add_name "Protector"
	add_name "OrngApricorn"
	add_name "CyanApricorn" ;e8
	add_name "GreyApricorn"
	add_name "PrplApricorn"
	add_name "ShnyApricorn"
	add_name "Wise Glasses"
	add_name "Mystery Tckt"
	add_name "Orphan Card"
	add_name "QR Scanner"
	add_name "Gas Mask" ;f0
	add_name "Fake ID"
	add_name "Fluffy Coat"
	add_name "Roof Card"
	add_name "Lab Card"
	add_name "Grapple Hook"
	add_name "Quick Ball"
	add_name "Dusk Ball"
	add_name "Repeat Ball" ;f8
	add_name "Timer Ball"
	add_name "Magnet Pass"
	add_name "Time Machine"
	add_name "TokenTracker"
	add_name "Power Herb"
	add_name "Item FE"
	add_name "Item FF"
	add_name "Item 0"
