TypeMatchup:
	;            NRM  FGT  FLY  PSN  GND  RCK  BRD  BUG  GST  STL  FRY  GAS  X12  SND  TRI  PSM  X16  X17  X18  ???  FIR  WTR  GRA  ELC  PSY  ICE  DRG  DRK
; Normal (NRM)
	type_matchup NTL, NTL, NTL, NTL, NTL, NVE, NTL, NTL, IMM, NVE, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL
; Fighting (FGT)
	type_matchup SE_, NTL, NVE, NVE, NTL, SE_, NTL, NVE, IMM, SE_, NVE, NVE, NTL, SE_, SE_, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NVE, SE_, NTL, SE_
; Flying (FLY)
	type_matchup NTL, SE_, NTL, NTL, NTL, NVE, NTL, SE_, NTL, NVE, NTL, NTL, NTL, NTL, NVE, NTL, NTL, NTL, NTL, NTL, NTL, NTL, SE_, NVE, NTL, NTL, NTL, NTL
; Poison (PSN)
	type_matchup NTL, NTL, NTL, NVE, NVE, NVE, NTL, NTL, NVE, IMM, SE_, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, SE_, NTL, NTL, NTL, NTL, NTL
; Ground (GND)
	type_matchup NTL, NTL, IMM, SE_, NTL, SE_, NTL, NVE, NTL, SE_, NTL, NVE, NTL, NTL, SE_, NTL, NTL, NTL, NTL, NTL, SE_, NTL, NVE, SE_, NTL, NTL, NTL, NTL
; Rock (RCK)
	type_matchup NTL, NVE, SE_, NTL, NVE, NTL, NTL, SE_, NTL, NVE, NTL, NTL, NTL, NVE, SE_, NTL, NTL, NTL, NTL, NTL, SE_, NTL, NTL, NTL, NTL, SE_, NTL, NTL
; Bird (BRD)
	type_matchup NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL
; Bug
	type_matchup NTL, NVE, NVE, NVE, NTL, NTL, NTL, NTL, NVE, NVE, NVE, NTL, NTL, SE_, NVE, NTL, NTL, NTL, NTL, NTL, NVE, NTL, SE_, NTL, SE_, NTL, NTL, SE_
; Ghost (GST)
	type_matchup IMM, NTL, NTL, NTL, NTL, NTL, NTL, NTL, SE_, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, SE_, NTL, NTL, NVE
; Steel (STL)
	type_matchup NTL, NTL, NTL, NTL, NTL, SE_, NTL, NTL, NTL, NVE, SE_, NTL, NTL, NVE, NVE, NTL, NTL, NTL, NTL, NTL, NVE, NVE, NTL, NVE, NTL, SE_, NTL, NTL
; Fairy (FRY)
	type_matchup NTL, SE_, NTL, NVE, NTL, NTL, NTL, NTL, NTL, NVE, NTL, NVE, NTL, NTL, NVE, NTL, NTL, NTL, NTL, NTL, NVE, NTL, NTL, NTL, NTL, NTL, SE_, SE_
; Gas
	type_matchup NTL, SE_, NTL, NTL, NTL, NVE, NTL, NTL, NTL, NTL, SE_, NTL, NTL, NVE, NTL, NTL, NTL, NTL, NTL, NTL, SE_, NTL, NVE, NTL, NTL, NVE, NTL, NTL
; XX12
	type_matchup NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL
; Sound (SND)
	type_matchup NTL, NVE, NTL, NTL, NTL, NTL, NTL, NVE, SE_, SE_, NTL, NTL, NTL, IMM, NTL, NTL, NTL, NTL, NTL, NTL, NTL, SE_, NTL, NTL, NTL, NTL, NTL, NTL
; Tri
	type_matchup NTL, NTL, SE_, NTL, IMM, NVE, NTL, SE_, NTL, NTL, NTL, SE_, NTL, SE_, NVE, NTL, NTL, NTL, NTL, NTL, NVE, NVE, SE_, NVE, NTL, NTL, NVE, NTL
; Prism (PSM)
	type_matchup NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL
; XX16
	type_matchup NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL
; XX17
	type_matchup NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL
; XX18
	type_matchup NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL
; Curse (???)
	type_matchup NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL
; Fire (FIR)
	type_matchup NTL, NTL, NTL, NTL, NTL, NVE, NTL, SE_, NTL, SE_, NTL, SE_, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NVE, NVE, SE_, NTL, NTL, SE_, NVE, NTL
; Water (WTR)
	type_matchup NTL, NTL, NTL, NTL, SE_, SE_, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NVE, SE_, NTL, NTL, NTL, NTL, NTL, SE_, NVE, NVE, NTL, NTL, NTL, NVE, NTL
; Grass (GRA)
	type_matchup NTL, NTL, NVE, NVE, SE_, SE_, NTL, NVE, NTL, NVE, NTL, SE_, NTL, NTL, NVE, NTL, NTL, NTL, NTL, NTL, NVE, SE_, NVE, NTL, NTL, NTL, NVE, NTL
; Electric (ELC)
	type_matchup NTL, NTL, SE_, NTL, IMM, NTL, NTL, NTL, NTL, NTL, NTL, SE_, NTL, SE_, NVE, NTL, NTL, NTL, NTL, NTL, NTL, SE_, NVE, NVE, NTL, NTL, NVE, NTL
; Psychic (PSY)
	type_matchup NTL, SE_, NTL, SE_, NTL, NTL, NTL, NTL, NTL, NVE, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NVE, NTL, NTL, IMM
; Ice
	type_matchup NTL, NTL, SE_, NTL, SE_, NTL, NTL, NTL, NTL, NVE, NTL, NTL, NTL, NTL, NVE, NTL, NTL, NTL, NTL, NTL, NVE, NVE, SE_, NTL, NTL, NVE, SE_, NTL
; Dragon (DRG)
	type_matchup NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NVE, IMM, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, SE_, NTL
; Dark (DRK)
	type_matchup NTL, NVE, NTL, NTL, NTL, NTL, NTL, NTL, SE_, NTL, NVE, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, NTL, SE_, NTL, NTL, NVE
	;            NRM  FGT  FLY  PSN  GND  RCK  BRD  BUG  GST  STL  FRY  GAS  X12  SND  TRI  PSM  X16  X17  X18  ???  FIR  WTR  GRA  ELC  PSY  ICE  DRG  DRK
