BlueGroup:
	; 1
	db "Blue@"

	db TRAINERTYPE_ITEM | TRAINERTYPE_MOVES

	db 85, EXEGGUTOR, HEAT_ROCK
		db SPRING_BUDS
		db SLEEP_POWDER
		db SYNTHESIS
		db SUNNY_DAY

	db 84, MACHAMP, SCOPE_LENS
		db EARTHQUAKE
		db DYNAMICPUNCH
		db FIRE_PUNCH
		db FOCUS_ENERGY

	db 86, RHYPERIOR, EXPERT_BELT
		db IRON_HEAD
		db EARTHQUAKE
		db ROCK_SLIDE
		db METALLURGY

	db 85, ARCANINE, SILK_SCARF
		db DRAGON_DANCE
		db FLAMETHROWER
		db EXTREMESPEED
		db WILD_CHARGE

	db 85, TYRANITAR, SMOOTH_ROCK
		db CRUNCH
		db ROCK_SLIDE
		db EARTHQUAKE
		db CROSS_CHOP

	db 87, PIDGEOT, LEFTOVERS
		db DOUBLE_EDGE
		db STEEL_WING
		db DOUBLE_TEAM
		db BRAVE_BIRD

	db -1
