BrownGroup:
	; 1
	db "Brown@"

	db TRAINERTYPE_ITEM | TRAINERTYPE_MOVES

	db 100, SCIZOR, LEFTOVERS
		db SWORDS_DANCE
		db AERIAL_ACE
		db QUICK_ATTACK
		db METAL_CLAW

	db 100, GOLEM, BURN_GUARD
		db EARTHQUAKE
		db ROCK_SLIDE
		db ROLLOUT
		db EXPLOSION

	db 100, MACHAMP, BLACKBELT
		db DRAIN_PUNCH
		db SWORDS_DANCE
		db BULLET_PUNCH
		db MACH_PUNCH

	db 100, VICTREEBEL, HEAT_ROCK
		db SUNNY_DAY
		db SOLARBEAM
		db STEEL_EATER
		db SLEEP_POWDER

	db 100, JOLTEON, SILVERPOWDER
		db THUNDERBOLT
		db SIGNAL_BEAM
		db CRYSTAL_BOLT
		db CALM_MIND

	db 100, CHARIZARD, CHARCOAL
		db FLARE_BLITZ
		db DRAGON_CLAW
		db DRAGON_DANCE
		db BURNING_MIST

	db -1
