BugsyGroup:
	; 1
	db "Bugsy@"

	db TRAINERTYPE_ITEM | TRAINERTYPE_MOVES

	db 81, FORRETRESS, SILK_SCARF
		db SPIKES
		db TOXIC
		db PROTECT
		db EXPLOSION

	db 79, BUTTERFREE, SAFE_GOGGLES
		db SLEEP_POWDER
		db STORM_FRONT
		db GIGA_DRAIN
		db SIGNAL_BEAM

	db 80, YANMEGA, WISE_GLASSES
		db AIR_SLASH
		db GIGA_DRAIN
		db ANCIENTPOWER
		db BUG_BUZZ

	db 82, ARMALDO, EXPERT_BELT
		db ROCK_SLIDE
		db WATERFALL
		db X_SCISSOR
		db SWORDS_DANCE

	db 84, SCIZOR, FOCUS_BAND
		db SWORDS_DANCE
		db BULLET_PUNCH
		db X_SCISSOR
		db AERIAL_ACE

	db -1
