ErnestGroup:
	; 1
	db "Ernest@"

	db TRAINERTYPE_ITEM | TRAINERTYPE_MOVES

	db 83, MAGMORTAR, EXPERT_BELT
		db FIRE_BLAST
		db THUNDERBOLT
		db EARTHQUAKE
		db REST

	db 84, TYPHLOSION, HEAT_ROCK
		db FIRE_BLAST
		db SHADOW_BALL
		db SUNNY_DAY
		db SOLARBEAM

	db 83, RAPIDASH, SITRUS_BERRY
		db FLARE_BLITZ
		db WILL_O_WISP
		db MORNING_SUN
		db MEGAHORN

	db 86, CAMERUPT, LEFTOVERS ; Solid Rock
		db DOUBLE_EDGE
		db MUD_SLAP
		db FIRE_BLAST
		db EARTHQUAKE

	db 88, CHARIZARD, DRAGON_FANG
		db DRAGON_DANCE
		db DRAGON_CLAW
		db FLARE_BLITZ
		db WING_ATTACK

	db -1
