GoldGroup:
	; 1
	db "Gold@"

	db TRAINERTYPE_ITEM | TRAINERTYPE_MOVES

	db 100, AMPHAROS, DRAGON_FANG
		db CRYSTAL_BOLT
		db DRAGON_PULSE
		db AGILITY
		db THUNDER

	db 100, UMBREON, LEFTOVERS
		db CALM_MIND
		db HEAL_BELL
		db DARK_PULSE
		db MOONLIGHT

	db 100, URSARING, SITRUS_BERRY
		db EARTHQUAKE
		db BELLY_DRUM
		db CRUNCH
		db QUICK_ATTACK

	db 100, MEGANIUM, HEAT_ROCK
		db SUNNY_DAY
		db SOLARBEAM
		db GROWTH
		db GIGA_DRAIN

	db 100, TYPHLOSION, MAGNET
		db FLAMETHROWER
		db SUNNY_DAY
		db THUNDERPUNCH
		db LAVA_POOL

	db 100, FERALIGATR, BURN_GUARD
		db RAIN_DANCE
		db WATERFALL
		db POISON_JAB
		db CRUNCH

	db -1
