RedGroup:
	; 1
	db "Red@"

	db TRAINERTYPE_ITEM | TRAINERTYPE_MOVES

	db 100, PIKACHU, LIGHT_BALL
		db THUNDERBOLT
		db SURF
		db QUICK_ATTACK
		db CRYSTAL_BOLT

	db 100, ESPEON, BURN_GUARD
		db CALM_MIND
		db PSYCHIC_M
		db SIGNAL_BEAM
		db POWER_GEM

	db 100, SNORLAX, LEFTOVERS
		db REST
		db SLEEP_TALK
		db DOUBLE_EDGE
		db EARTHQUAKE

	db 100, VENUSAUR, HEAT_ROCK
		db SUNNY_DAY
		db SOLARBEAM
		db SPRING_BUDS
		db STEEL_EATER

	db 100, CHARIZARD, POWER_HERB
		db MORNING_SUN
		db FIRE_BLAST
		db SOLARBEAM
		db LAVA_POOL

	db 100, BLASTOISE, LUM_BERRY
		db HYDRO_PUMP
		db ICE_BEAM
		db RAIN_DANCE
		db BOIL

	db -1
