WhitneyGroup:
	; 1
	db "Whitney@"

	db TRAINERTYPE_ITEM | TRAINERTYPE_MOVES

	db 79, WIGGLYTUFF, SILK_SCARF
		db HYPER_VOICE
		db VOID_SPHERE
		db CHARM
		db MOONBLAST

	db 81, BLISSEY, LEFTOVERS
		db TOXIC
		db SEISMIC_TOSS
		db PROTECT
		db SOFTBOILED

	db 80, TOGEKISS, PRZ_GUARD
		db MOONBLAST
		db NASTY_PLOT
		db AIR_SLASH
		db THUNDER_WAVE

	db 82, LOPUNNY, SITRUS_BERRY
		db ATTRACT
		db HI_JUMP_KICK
		db PLAY_ROUGH
		db RETURN

	db 83, SNORLAX, CHESTO_BERRY
		db BELLY_DRUM
		db THUNDERPUNCH
		db EARTHQUAKE
		db REST

	db -1
