SECTION "Battle Tower Map Scripts", ROMX
; THESE MUST ALL BE IN THE SAME BANK
INCLUDE "maps/BattleTowerEntrance.asm"
INCLUDE "maps/BattleTowerElevator.asm"
INCLUDE "maps/BattleTowerHallway.asm"
INCLUDE "maps/BattleTowerBattleRoom.asm"

SECTION "Map Scripts 1", ROMX
INCLUDE "maps/ApartmentsF1.asm"
INCLUDE "maps/ApartmentsF2.asm"
INCLUDE "maps/ApartmentsF3.asm"
INCLUDE "maps/Apartments1C.asm"
INCLUDE "maps/SoutherlyHouse.asm"
INCLUDE "maps/SoutherlyHouse2.asm"
INCLUDE "maps/TunodWaterway.asm"
INCLUDE "maps/TradeCenter.asm"
INCLUDE "maps/TimeCapsule.asm"
INCLUDE "maps/BattleArcadeBattleroom.asm"
INCLUDE "maps/SaffronCopycatsHouse.asm"
INCLUDE "maps/Route49Gate.asm"
INCLUDE "maps/Route78EastExit.asm"
INCLUDE "maps/Route81Eastgate.asm"
INCLUDE "maps/Route81Goodrod.asm"
INCLUDE "maps/Route86UndergroundPath.asm"
INCLUDE "maps/FarawayIslandOutside.asm"
INCLUDE "maps/FarawayIslandInside.asm"
INCLUDE "maps/PhloxEntry.asm"
INCLUDE "maps/MtEmberEntrance.asm"
INCLUDE "maps/Route86DockExit.asm"
INCLUDE "maps/MersonPokecenter.asm"
INCLUDE "maps/SouthRijonGate.asm"
INCLUDE "maps/EmberBrook.asm"
INCLUDE "maps/OlcanPokecenter.asm"

SECTION "Map Scripts 2", ROMX
INCLUDE "maps/AzaleaTown.asm"
INCLUDE "maps/AzaleaPokecenter.asm"
INCLUDE "maps/AzaleaMart.asm"
INCLUDE "maps/AzaleaGym.asm"
INCLUDE "maps/AzaleaCharcoal.asm"
INCLUDE "maps/AzaleaKurt.asm"
INCLUDE "maps/AzaleaKurtBasement.asm"
INCLUDE "maps/IlexForest.asm"
INCLUDE "maps/GoldenrodCity.asm"
INCLUDE "maps/GoldenrodCape.asm"
INCLUDE "maps/GoldenrodCapeGate.asm"
INCLUDE "maps/GoldenrodPokecenter.asm"
INCLUDE "maps/GoldenrodMart.asm"
INCLUDE "maps/GoldenrodMagnetTrain.asm"
INCLUDE "maps/GoldenrodGym.asm"
INCLUDE "maps/GoldenrodUndergroundEntryA.asm"
INCLUDE "maps/GoldenrodUndergroundEntryB.asm"
INCLUDE "maps/GoldenrodUnderground.asm"
INCLUDE "maps/GoldenrodSwitches.asm"
INCLUDE "maps/GoldenrodStorage.asm"
INCLUDE "maps/GoldenrodBill.asm"
INCLUDE "maps/SaffronGates.asm"
INCLUDE "maps/AcaniaHouse.asm"
INCLUDE "maps/AcaniaTM63.asm"
INCLUDE "maps/RuinsEntry.asm"
INCLUDE "maps/ProvincialPark.asm"
INCLUDE "maps/PhaceliaWestExit.asm"
INCLUDE "maps/SaxifrageWardensHouse.asm"
INCLUDE "maps/Route74.asm"
INCLUDE "maps/Route75.asm"
INCLUDE "maps/Route76.asm"
INCLUDE "maps/Route77.asm"
INCLUDE "maps/SoutherlyMagnetTrain.asm"
INCLUDE "maps/OlcanChine.asm"

SECTION "Map Scripts 3", ROMX
INCLUDE "maps/IntroOutside.asm"
INCLUDE "maps/IntroCave.asm"
INCLUDE "maps/CaperRidge.asm"
INCLUDE "maps/CaperPokecenter.asm"
INCLUDE "maps/CaperMart.asm"
INCLUDE "maps/CaperHouse.asm"
INCLUDE "maps/OxalisCity.asm"
INCLUDE "maps/OxalisGym.asm"
INCLUDE "maps/OxalisMart.asm"
INCLUDE "maps/TrainerHouse.asm"
INCLUDE "maps/TrainerHouseB1F.asm"
INCLUDE "maps/SpurgeCity.asm"
; linked, do not separate
INCLUDE "maps/SpurgeGymB1F.asm"
INCLUDE "maps/SpurgeGymB2F.asm"
INCLUDE "maps/SpurgeGymB2FSidescroll.asm"
; end linked section
INCLUDE "maps/HeathVillage.asm"
INCLUDE "maps/HeathGym.asm"
INCLUDE "maps/HeathGymGate.asm"
INCLUDE "maps/HeathHouseTM30.asm"
INCLUDE "maps/HeathHouseTM35.asm"
INCLUDE "maps/HeathInn.asm"
INCLUDE "maps/MtEmberRoom1.asm"
INCLUDE "maps/BotanHouse.asm"
INCLUDE "maps/Route55.asm"
INCLUDE "maps/Route72Gate.asm"
INCLUDE "maps/MtEmberRoom2.asm"
INCLUDE "maps/EspoClearing.asm"

SECTION "Map Scripts 4", ROMX
INCLUDE "maps/LaurelCity.asm"
INCLUDE "maps/LaurelPokecenter.asm"
INCLUDE "maps/LaurelMart.asm"
INCLUDE "maps/LaurelGym.asm"
INCLUDE "maps/LaurelLab.asm"
INCLUDE "maps/LaurelNamerater.asm"
INCLUDE "maps/LaurelStick.asm"
INCLUDE "maps/LaurelGate.asm"
INCLUDE "maps/MagikarpCavernsRapids.asm"
INCLUDE "maps/MagikarpCavernsEnd.asm"
INCLUDE "maps/Route87.asm"
INCLUDE "maps/ToreniaCity.asm"
INCLUDE "maps/ToreniaPokecenter.asm"
INCLUDE "maps/ToreniaMart.asm"
INCLUDE "maps/ToreniaGym.asm"
INCLUDE "maps/ToreniaPachisi.asm"
INCLUDE "maps/ToreniaDrifloomTrade.asm"
INCLUDE "maps/ToreniaCelebrity.asm"
INCLUDE "maps/ToreniaGate.asm"
INCLUDE "maps/PhaceliaCity.asm"
INCLUDE "maps/PhaceliaPoliceF2.asm"
INCLUDE "maps/PhaceliaPoliceF1.asm"
INCLUDE "maps/PhaceliaEastExit.asm"
INCLUDE "maps/PhaceliaPokecenter.asm"
INCLUDE "maps/PhaceliaMart.asm"
INCLUDE "maps/PhaceliaGym.asm"
INCLUDE "maps/PhaceliaMoveDeleter.asm"
INCLUDE "maps/PhaceliaSolrockTrade.asm"
INCLUDE "maps/PhaceliaTM20.asm"
INCLUDE "maps/SpurgeGymHouse.asm"
INCLUDE "maps/HeathGymUnderground.asm"
INCLUDE "maps/HappinessRater.asm"

SECTION "Map Scripts 5", ROMX
INCLUDE "maps/Route34Gate.asm"
INCLUDE "maps/SaxifragePokecenter.asm"
INCLUDE "maps/SaxifrageMart.asm"
INCLUDE "maps/SaxifrageExits.asm"
INCLUDE "maps/SaxifrageGym.asm"
INCLUDE "maps/PrisonB1F.asm"
INCLUDE "maps/PrisonF1.asm"
INCLUDE "maps/PrisonF2.asm"
INCLUDE "maps/PrisonPaths.asm"
INCLUDE "maps/PrisonBaths.asm"
INCLUDE "maps/PrisonCafeteria.asm"
INCLUDE "maps/PrisonElectricChair.asm"
INCLUDE "maps/PrisonWorkout.asm"
INCLUDE "maps/PrisonRoof.asm"
INCLUDE "maps/PhloxMart.asm"
INCLUDE "maps/PhloxPokecenter.asm"
INCLUDE "maps/Orphanage.asm"
INCLUDE "maps/BattleCenter.asm"
INCLUDE "maps/PokecenterBackroom.asm"
INCLUDE "maps/SoutherlyGym.asm"
INCLUDE "maps/SpurgeGym1F.asm"

SECTION "Map Scripts 6", ROMX
INCLUDE "maps/PhloxTown.asm"
INCLUDE "maps/PhloxLabB1F.asm"
INCLUDE "maps/PhloxLab1F.asm"
INCLUDE "maps/PhloxMyles.asm"
INCLUDE "maps/AcaniaDocks.asm"
INCLUDE "maps/FirelightF1.asm"
INCLUDE "maps/MilosGreenOrb.asm"
INCLUDE "maps/MilosRayquaza.asm"
INCLUDE "maps/MoundUpperArea.asm"
INCLUDE "maps/FirelightGroudon.asm"
INCLUDE "maps/PhanceroRoom.asm"
INCLUDE "maps/AcaniaLighthouseF1.asm"
INCLUDE "maps/AcaniaLighthouseF2.asm"
INCLUDE "maps/AcaniaGym.asm"
INCLUDE "maps/Route82Gate.asm"
INCLUDE "maps/SoutherlyAirport.asm"
INCLUDE "maps/OlcanChineEntrance.asm"

SECTION "Map Scripts 7", ROMX
INCLUDE "maps/Route47.asm"
INCLUDE "maps/Route52Gate.asm"
INCLUDE "maps/Route55GateUnderground.asm"
INCLUDE "maps/Route56.asm"
INCLUDE "maps/Route57.asm"
INCLUDE "maps/Route57Gym.asm"
INCLUDE "maps/Route58.asm"
INCLUDE "maps/Route58Gate.asm"
INCLUDE "maps/Route59.asm"
INCLUDE "maps/Route59Gate.asm"
INCLUDE "maps/Route60.asm"
INCLUDE "maps/Route60Gate.asm"
INCLUDE "maps/Route61.asm"
INCLUDE "maps/Route61GateSouth.asm"
INCLUDE "maps/Route61GateNorth.asm"
INCLUDE "maps/Route61House.asm"
INCLUDE "maps/Route61House2.asm"
INCLUDE "maps/Route62.asm"
INCLUDE "maps/Route62Gate.asm"
INCLUDE "maps/Route63.asm"
INCLUDE "maps/Route64.asm"
INCLUDE "maps/Route66.asm"
INCLUDE "maps/Route67.asm"
INCLUDE "maps/Route81Pokecenter.asm"
INCLUDE "maps/SilphWarehouseF2.asm"
INCLUDE "maps/PowerPlantLobby.asm"
INCLUDE "maps/PowerPlant1F.asm"
INCLUDE "maps/PowerPlant2F.asm"
INCLUDE "maps/PowerPlant3F.asm"
INCLUDE "maps/MersonCaveB1F.asm"
INCLUDE "maps/MersonCaveB2F.asm"
INCLUDE "maps/MersonCaveB3F.asm"
INCLUDE "maps/SilkTunnel1F.asm"
INCLUDE "maps/SilkTunnelB1F.asm"
INCLUDE "maps/SilkTunnelB2F.asm"
INCLUDE "maps/SilkTunnelB3F.asm"
INCLUDE "maps/SilkTunnelB4F.asm"
INCLUDE "maps/CastroForest.asm"
INCLUDE "maps/CastroForestGateSouth.asm"
INCLUDE "maps/MtBoulderB1F.asm"
INCLUDE "maps/MtBoulderB2F.asm"
INCLUDE "maps/RijonUndergroundHorizontal.asm"
INCLUDE "maps/RijonUndergroundVertical.asm"
INCLUDE "maps/RijonHiddenBasement.asm"
INCLUDE "maps/SenecaCavernsF1.asm"
INCLUDE "maps/SenecaCavernsB1F.asm"
INCLUDE "maps/SenecaCavernsB2F.asm"
INCLUDE "maps/HauntedForestGate.asm"
INCLUDE "maps/HauntedForest.asm"
INCLUDE "maps/HauntedMansion.asm"
INCLUDE "maps/DreamSequence.asm"
INCLUDE "maps/DreamNewBark.asm"
INCLUDE "maps/AcaniaPokecenter.asm"
INCLUDE "maps/AcquaLabBasementPath.asm"
INCLUDE "maps/MilosB2F.asm"
INCLUDE "maps/LaurelForestGates.asm"
INCLUDE "maps/SaxifrageIsland.asm"

SECTION "Map Scripts 8", ROMX
INCLUDE "maps/Route67Gate.asm"
INCLUDE "maps/Route67Pokecenter.asm"
INCLUDE "maps/Route67House.asm"
INCLUDE "maps/Route69South.asm"
INCLUDE "maps/Route69IlkBrotherHouse.asm"
INCLUDE "maps/HaywardEarthquakeLab.asm"
INCLUDE "maps/HaywardHouse.asm"
INCLUDE "maps/MysteryZone.asm"
INCLUDE "maps/MysteryZoneLeagueLobby.asm"
INCLUDE "maps/MysteryZoneLeagueBrown.asm"
INCLUDE "maps/MysteryZoneLeagueGold.asm"
INCLUDE "maps/MysteryZoneLeagueRed.asm"
INCLUDE "maps/MysteryZoneLeagueAirport.asm"
INCLUDE "maps/SilkTunnelB5F.asm"
INCLUDE "maps/FirelightItemRoom.asm"
INCLUDE "maps/ToreniaMagnetTrain.asm"
INCLUDE "maps/Route77Pokecenter.asm"
INCLUDE "maps/Route77DaycareHouse.asm"
INCLUDE "maps/Route77DaycareGarden.asm"

SECTION "Map Scripts 9", ROMX
INCLUDE "maps/Route78.asm"
INCLUDE "maps/Route79.asm"
INCLUDE "maps/Route80.asm"
INCLUDE "maps/Route80Nobu.asm"
INCLUDE "maps/Route81.asm"
INCLUDE "maps/Route81Northgate.asm"
INCLUDE "maps/Route82.asm"
INCLUDE "maps/Route82Cave.asm"
INCLUDE "maps/Route83.asm"
INCLUDE "maps/Route84.asm"
INCLUDE "maps/Route85.asm"
INCLUDE "maps/Route86.asm"
INCLUDE "maps/Route86Dock.asm"
INCLUDE "maps/AcquaStart.asm"
INCLUDE "maps/AcquaTutorial.asm"
INCLUDE "maps/AcquaExitChamber.asm"
INCLUDE "maps/AcquaHiTide.asm"
INCLUDE "maps/AcquaMedTide.asm"
INCLUDE "maps/AcquaLowTide.asm"
INCLUDE "maps/AcquaRoom.asm"
INCLUDE "maps/SpurgeGameCorner.asm"
INCLUDE "maps/EagulouGymF1.asm"
INCLUDE "maps/SaffronCity.asm"
INCLUDE "maps/Route34.asm"
INCLUDE "maps/IlexForestGate.asm"

SECTION "Map Scripts 10", ROMX
INCLUDE "maps/LaurelForestBeach.asm"
INCLUDE "maps/LaurelForestCharizardCave.asm"
INCLUDE "maps/LaurelForestLab.asm"
INCLUDE "maps/MoundF1.asm"
INCLUDE "maps/MoundB1F.asm"
; linked, do not separate
INCLUDE "maps/MoundB2F.asm"
INCLUDE "maps/MoundB3F.asm"
; end linked section
INCLUDE "maps/ProvincialParkGate.asm"
INCLUDE "maps/ProvincialParkContest.asm"
INCLUDE "maps/MilosF1.asm"
INCLUDE "maps/MilosB1F.asm"
INCLUDE "maps/Route50.asm"
INCLUDE "maps/Route51.asm"
INCLUDE "maps/Route52.asm"
INCLUDE "maps/IlksLab.asm"

SECTION "Map Scripts 11", ROMX
INCLUDE "maps/MilosB2Fb.asm"
INCLUDE "maps/RuinsOutside.asm"
INCLUDE "maps/RuinsRoof.asm"
INCLUDE "maps/FirelightPalletPathB1F.asm"
INCLUDE "maps/FirelightPalletPath1F.asm"
INCLUDE "maps/FirelightRooms.asm"
INCLUDE "maps/CastroValley.asm"
INCLUDE "maps/CastroGym.asm"
INCLUDE "maps/CastroPokecenter.asm"
INCLUDE "maps/CastroMansion.asm"
INCLUDE "maps/CastroDock.asm"
INCLUDE "maps/RijonLeagueYuki.asm"
INCLUDE "maps/RijonLeagueSora.asm"
INCLUDE "maps/RijonLeagueDaichi.asm"
INCLUDE "maps/EagulouCity.asm"
INCLUDE "maps/EagulouMart.asm"
INCLUDE "maps/SilphCoB1F.asm"
INCLUDE "maps/Route73Gate.asm"

SECTION "Map Scripts 12", ROMX
INCLUDE "maps/RuinsF1.asm"
INCLUDE "maps/RuinsF4.asm"
INCLUDE "maps/RuinsF5.asm"
INCLUDE "maps/RuinsB1F.asm"
INCLUDE "maps/Clathrite1F.asm"
INCLUDE "maps/ClathriteB1F.asm"
INCLUDE "maps/ClathriteB2F.asm"
INCLUDE "maps/ClathriteKyogre.asm"
INCLUDE "maps/NaljoBorderEast.asm"
INCLUDE "maps/NaljoBorderWest.asm"
INCLUDE "maps/NaljoBorderWarpRoom.asm"
INCLUDE "maps/LongTunnelPath.asm"
INCLUDE "maps/LongTunnelSidescroll.asm"
INCLUDE "maps/SeashoreCity.asm"
INCLUDE "maps/SeashoreGym.asm"
INCLUDE "maps/SeashoreMura.asm"
INCLUDE "maps/BrownsHouseF1.asm"
INCLUDE "maps/BrownsHouseF2.asm"
INCLUDE "maps/GravelTown.asm"
INCLUDE "maps/GravelMart.asm"
INCLUDE "maps/JensLab.asm"
INCLUDE "maps/MersonCity.asm"
INCLUDE "maps/MersonGym.asm"
INCLUDE "maps/MersonMart.asm"
INCLUDE "maps/MersonHouse.asm"
INCLUDE "maps/MersonBirdHouse.asm"
INCLUDE "maps/LaurelForestMain.asm"
INCLUDE "maps/Route69SouthGate.asm"
INCLUDE "maps/Route70.asm"
INCLUDE "maps/Route71West.asm"
INCLUDE "maps/Route71East.asm"
INCLUDE "maps/Route72.asm"
INCLUDE "maps/Route73.asm"
INCLUDE "maps/MilosTowerClimb.asm"

SECTION "Map Scripts 13", ROMX
INCLUDE "maps/MersonGoldTokenExchange.asm"
INCLUDE "maps/HaywardMartF1.asm"
INCLUDE "maps/HaywardMartF2.asm"
INCLUDE "maps/HaywardMartF3.asm"
INCLUDE "maps/HaywardMartF4.asm"
INCLUDE "maps/HaywardMartF5.asm"
INCLUDE "maps/HaywardMartElevator.asm"
INCLUDE "maps/HaywardMartF6.asm"
INCLUDE "maps/HaywardPokecenter.asm"
INCLUDE "maps/HaywardMawile.asm"
INCLUDE "maps/OwsauriCity.asm"
INCLUDE "maps/OwsauriGym.asm"
INCLUDE "maps/OwsauriGameCorner.asm"
INCLUDE "maps/OwsauriMart.asm"
INCLUDE "maps/OwsauriPokecenter.asm"
INCLUDE "maps/OwsauriNamerater.asm"
INCLUDE "maps/OwsauriHouse.asm"
INCLUDE "maps/OwsauriStatEXP.asm"
INCLUDE "maps/MoragaTown.asm"
INCLUDE "maps/MoragaGym.asm"
INCLUDE "maps/MoragaDiner.asm"
INCLUDE "maps/MoragaGateUnderground.asm"
INCLUDE "maps/MoragaMart.asm"
INCLUDE "maps/MoragaPokecenter.asm"
INCLUDE "maps/MoragaHouse.asm"
INCLUDE "maps/MoragaMoveRelearner.asm"
INCLUDE "maps/JaeruCity.asm"
INCLUDE "maps/JaeruGym.asm"
INCLUDE "maps/JaeruGate.asm"
INCLUDE "maps/JaeruMart.asm"
INCLUDE "maps/JaeruGoldTokenVendor.asm"
INCLUDE "maps/BotanMart.asm"
INCLUDE "maps/BotanPokecenter.asm"
INCLUDE "maps/BotanPachisi.asm"
INCLUDE "maps/CastroGate.asm"
INCLUDE "maps/FirelightMinecart.asm"

SECTION "Map Scripts 14", ROMX
INCLUDE "maps/SpurgeMart.asm"
INCLUDE "maps/BotanCity.asm"
INCLUDE "maps/BotanMagnetTrain.asm"
INCLUDE "maps/Route52GateUnderground.asm"
INCLUDE "maps/Route52House.asm"
INCLUDE "maps/Route53.asm"
INCLUDE "maps/Route54.asm"
INCLUDE "maps/Route56Gate.asm"
INCLUDE "maps/Route56GateUnderground.asm"
INCLUDE "maps/SilphWarehouseF1.asm"
INCLUDE "maps/SilphWarehouseB1F.asm"
INCLUDE "maps/Apartments2D.asm"
INCLUDE "maps/SeviiIsland1.asm"
INCLUDE "maps/SeviiIsland2.asm"
INCLUDE "maps/SeviiIsland3.asm"
INCLUDE "maps/GoldenrodMartB1F.asm"
INCLUDE "maps/SoutherlyMart.asm"

SECTION "Map Scripts 15", ROMX
INCLUDE "maps/CastroTyrogueTrade.asm"
INCLUDE "maps/EagulouPark3.asm"
INCLUDE "maps/SoutherlyBattleHouse.asm"
INCLUDE "maps/SoutherlyPokecenter.asm"
INCLUDE "maps/OxalisSalon.asm"
INCLUDE "maps/PhloxBingo.asm"
INCLUDE "maps/RijonLeagueOutside.asm"
INCLUDE "maps/RijonLeagueInside.asm"
INCLUDE "maps/RijonLeagueParty.asm"
INCLUDE "maps/RijonLeagueChampionRoom.asm"
INCLUDE "maps/PrisonContainment.asm"
INCLUDE "maps/Route49.asm"
INCLUDE "maps/Route50Gate.asm"
INCLUDE "maps/HauntedMansionBasement.asm"
INCLUDE "maps/OlcanDockExit.asm"
INCLUDE "maps/OlcanDock.asm"

SECTION "Map Scripts 16", ROMX
INCLUDE "maps/PhloxLab2F.asm"
INCLUDE "maps/PhloxLab3F.asm"
INCLUDE "maps/Route48.asm"
INCLUDE "maps/MtEmber.asm"
INCLUDE "maps/OlcanIsle.asm"
INCLUDE "maps/EspoForest.asm"
INCLUDE "maps/MagikarpCavernsMain.asm"
INCLUDE "maps/BattleArcadeLobby.asm"

SECTION "Map Scripts small 1", ROMX
INCLUDE "maps/RuinsF3.asm"
INCLUDE "maps/HeathGymHouse.asm"

SECTION "Map Scripts small 2", ROMX
INCLUDE "maps/GoldenrodGameCorner.asm"
INCLUDE "maps/GoldenrodHappinessMoveTeacher.asm"
INCLUDE "maps/SaffronPokecenter.asm"
INCLUDE "maps/SilphCo.asm"
INCLUDE "maps/AcquaPhloxEntrance.asm"
INCLUDE "maps/Route77Jewelers.asm"
INCLUDE "maps/Apartments1B.asm"

SECTION "Map Scripts small 3", ROMX
INCLUDE "maps/JaeruPokecenter.asm"
INCLUDE "maps/SaffronMart.asm"
INCLUDE "maps/SaffronFightingDojo.asm"

SECTION "Map Scripts small 4", ROMX
INCLUDE "maps/HeathHouseWeaver.asm"
INCLUDE "maps/SouthSoutherly.asm"
INCLUDE "maps/SaffronMagnetTrain.asm"
INCLUDE "maps/EmberBrookGate.asm"
INCLUDE "maps/Route69North.asm"
INCLUDE "maps/Route69NorthGate.asm"

SECTION "Map Scripts small 5", ROMX
INCLUDE "maps/HaywardCity.asm"

SECTION "Map Scripts small 6", ROMX
INCLUDE "maps/SaffronGym.asm"
INCLUDE "maps/AcaniaMart.asm"
INCLUDE "maps/SpurgePokecenter.asm"

SECTION "Map Scripts small 7", ROMX
INCLUDE "maps/Route65.asm"
INCLUDE "maps/Route68.asm"
INCLUDE "maps/Route82Monkey.asm"
INCLUDE "maps/RijonLeagueLance.asm"
INCLUDE "maps/MersonHouse2.asm"
INCLUDE "maps/SaffronMrPsychic.asm"
INCLUDE "maps/RuinsF2.asm"

SECTION "Map Scripts small 8", ROMX
INCLUDE "maps/CastroDockPath.asm"
INCLUDE "maps/EagulouParkGate.asm"

SECTION "Map Scripts small 9", ROMX
INCLUDE "maps/SoutherlyCity.asm"
INCLUDE "maps/HeathGate.asm"
INCLUDE "maps/OxalisPokecenter.asm"

SECTION "Map Scripts small 10", ROMX
INCLUDE "maps/CastroMart.asm"

SECTION "Map Scripts small 11", ROMX
INCLUDE "maps/SpurgeHouse.asm"

SECTION "Map Scripts small 12", ROMX
INCLUDE "maps/EagulouPark2.asm"
INCLUDE "maps/EagulouGymB1F.asm"
INCLUDE "maps/EagulouPokecenter.asm"
INCLUDE "maps/EagulouPark1.asm"
INCLUDE "maps/RijonLeagueMura.asm"
INCLUDE "maps/CastroSuperRod.asm"

SECTION "Map Scripts Laurel Forest Pokemon Only", ROMX
INCLUDE "maps/LaurelForestPokemonOnly.asm"
INCLUDE "maps/LaurelForestPokemonOnly_Triggers.asm"
INCLUDE "maps/LaurelForestPokemonOnly_BlockingCharizard.asm"
INCLUDE "maps/LaurelForestPokemonOnly_PikachuQuest.asm"
INCLUDE "maps/LaurelForestPokemonOnly_CaterpieQuest.asm"
INCLUDE "maps/LaurelForestPokemonOnly_CharmanderQuest.asm"

; DO NOT ADD ANYTHING BELOW THIS LINE
; DO NOT ADD ANTYHING BELOW THIS LINE
; DO NOT ADD ANYTHING BELOW THIS LINE
; if you need to add new map scripts, find a section where they fit and add them there
