SenecaCavernsB2F_MapScriptHeader:
 ;trigger count
	db 0
 ;callback count
	db 0

SenecaCavernsB2FHiddenItem:
	dw EVENT_SENECACAVERNSB2F_HIDDENITEM_HP_UP
	db HP_UP

SenecaCavernsB2FArticuno:
	faceplayer
	opentext
	writetext .text
	cry ARTICUNO
	setlasttalked 255
	writecode VAR_BATTLETYPE, BATTLETYPE_NORMAL
	writecode VAR_EVENTMONRESPAWN, EVENTMONRESPAWN_ARTICUNO
	loadwildmon ARTICUNO, 50
	startbattle
	reloadmapafterbattle
	setevent EVENT_ARTICUNO
	disappear 2
	end

.text
	ctxt "Gyaoo!!!"
	done

SenecaCavernsB2F_MapEventHeader:: db 0, 0

.Warps
	db 10
	warp_def $8, $9, 2, SENECACAVERNSB1F
	warp_def $8, $12, 5, SENECACAVERNSB2F
	warp_def $10, $7, 6, SENECACAVERNSB2F
	warp_def $1e, $4, 2, SENECACAVERNSF1
	warp_def $12, $24, 2, SENECACAVERNSB2F
	warp_def $20, $e, 3, SENECACAVERNSB2F
	warp_def $26, $20, 8, SENECACAVERNSB2F
	warp_def $28, $2, 7, SENECACAVERNSB2F
	warp_def $2e, $a, 10, SENECACAVERNSB2F
	warp_def $2e, $24, 9, SENECACAVERNSB2F

.CoordEvents
	db 0

.BGEvents
	db 1
	signpost 30, 2, SIGNPOST_ITEM, SenecaCavernsB2FHiddenItem

.ObjectEvents
	db 11
	person_event SPRITE_ARTICUNO, 46, 24, SPRITEMOVEDATA_POKEMON, 0, 0, -1, -1, PAL_OW_BLUE, PERSONTYPE_SCRIPT, 0, SenecaCavernsB2FArticuno, EVENT_ARTICUNO
	person_event SPRITE_POKE_BALL, 15, 9, SPRITEMOVEDATA_ITEM_TREE, 0, 0, -1, -1, PAL_OW_YELLOW, PERSONTYPE_TMHMBALL, TM_HIDDEN_POWER, 0, EVENT_SENECACAVERNSB2F_NPC_2
	person_event SPRITE_BOULDER, 43, 7, SPRITEMOVEDATA_STRENGTH_BOULDER, 0, 0, -1, -1, PAL_OW_BROWN, PERSONTYPE_JUMPSTD, 0, strengthboulder, -1
	person_event SPRITE_BOULDER, 25, 37, SPRITEMOVEDATA_STRENGTH_BOULDER, 0, 0, -1, -1, PAL_OW_BROWN, PERSONTYPE_JUMPSTD, 0, strengthboulder, -1
	person_event SPRITE_BOULDER, 33, 31, SPRITEMOVEDATA_STRENGTH_BOULDER, 0, 0, -1, -1, PAL_OW_BROWN, PERSONTYPE_JUMPSTD, 0, strengthboulder, -1
	person_event SPRITE_BOULDER, 31, 6, SPRITEMOVEDATA_STRENGTH_BOULDER, 0, 0, -1, -1, PAL_OW_BROWN, PERSONTYPE_JUMPSTD, 0, strengthboulder, -1
	person_event SPRITE_BOULDER, 44, 9, SPRITEMOVEDATA_STRENGTH_BOULDER, 0, 0, -1, -1, PAL_OW_BROWN, PERSONTYPE_JUMPSTD, 0, strengthboulder, -1
	person_event SPRITE_BOULDER, 39, 30, SPRITEMOVEDATA_STRENGTH_BOULDER, 0, 0, -1, -1, PAL_OW_BROWN, PERSONTYPE_JUMPSTD, 0, strengthboulder, -1
	person_event SPRITE_POKE_BALL, 33, 6, SPRITEMOVEDATA_ITEM_TREE, 0, 0, -1, -1, PAL_OW_RED, PERSONTYPE_ITEMBALL, 1, LEFTOVERS, EVENT_SENECACAVERNSB2F_ITEM_LEFTOVERS
	person_event SPRITE_POKE_BALL, 4, 24, SPRITEMOVEDATA_ITEM_TREE, 0, 0, -1, -1, PAL_OW_RED, PERSONTYPE_ITEMBALL, 2, RARE_CANDY, EVENT_SENECACAVERNSB2F_ITEM_RARE_CANDIES
	person_event SPRITE_POKE_BALL, 33, 30, SPRITEMOVEDATA_ITEM_TREE, 0, 0, -1, -1, PAL_OW_RED, PERSONTYPE_ITEMBALL, 1, MAX_REVIVE, EVENT_SENECACAVERNSB2F_ITEM_MAX_REVIVE
