MACRO command
	enum \1_command
\1 equs "db \1_command"
ENDM

	enum_start 1

	command checkturn               ; 01
	command checkobedience          ; 02
	command usedmovetext            ; 03
	command doturn                  ; 04
	command critical                ; 05
	command damagestats             ; 06
	command typematchup             ; 07
	command damagevariation         ; 08
	command checkhit                ; 09
	command lowersub                ; 0a
	command hittargetnosub          ; 0b
	command raisesub                ; 0c
	command failuretext             ; 0d
	command checkfaint              ; 0e
	command criticaltext            ; 0f
	command supereffectivetext      ; 10
	command strikeback              ; 11
	command buildopponentrage       ; 12
	command poisontarget            ; 13
	command sleeptarget             ; 14
	command draintarget             ; 15
	command eatdream                ; 16
	command burntarget              ; 17
	command freezetarget            ; 18
	command paralyzetarget          ; 19
	command selfdestruct            ; 1a
	command mirrormove              ; 1b
	command statup                  ; 1c
	command statdown                ; 1d
	command swagger                 ; 1e
	command conversion              ; 1f
	command resetstats              ; 20
	command forceswitch             ; 21
	command endloop                 ; 22
	command flinchtarget            ; 23
	command pressure                ; 24
	command recoil                  ; 25
	command mist                    ; 26
	command focusenergy             ; 27
	command confuse                 ; 28
	command confusetarget           ; 29
	command heal                    ; 2a
	command transform               ; 2b
	command screen                  ; 2c
	command poison                  ; 2d
	command paralyze                ; 2e
	command burn                    ; 2f
	command substitute              ; 30
	command rechargenextturn        ; 31
	command metronome               ; 32
	command leechseed               ; 33
	command splash                  ; 34
	command disable                 ; 35
	command cleartext               ; 36
	command charge                  ; 37
	command checkcharge             ; 38
	command traptarget              ; 39
	command bulkup                  ; 3a
	command cosmicpower             ; 3b
	command calmmind                ; 3c
	command rampage                 ; 3d
	command checkrampage            ; 3e
	command constantdamage          ; 3f
	command counter                 ; 40
	command encore                  ; 41
	command thunderfang             ; 42
	command conversion2             ; 43
	command lockon                  ; 44
	command fatiguetext             ; 45
	command sleeptalk               ; 46
	command destinybond             ; 47
	command spite                   ; 48
	command falseswipe              ; 49
	command healbell                ; 4a
	command kingsrock               ; 4b
	enum skip                       ; 4c
	enum skip                       ; 4d
	command thief                   ; 4e
	command arenatrap               ; 4f
	command nightmare               ; 50
	command defrost                 ; 51
	command curse                   ; 52
	command protect                 ; 53
	command spikes                  ; 54
	command foresight               ; 55
	command perishsong              ; 56
	command startsandstorm          ; 57
	command starthail               ; 58
	command endure                  ; 59
	command checkcurl               ; 5a
	command rolloutpower            ; 5b
	command finalchance             ; 5c
	command furycutter              ; 5d
	command attract                 ; 5e
	command happinesspower          ; 5f
	enum skip                       ; 60
	command damagecalc              ; 61
	command frustrationpower        ; 62
	command safeguard               ; 63
	command checksafeguard          ; 64
	command getmagnitude            ; 65
	command batonpass               ; 66
	command pursuit                 ; 67
	command clearhazards            ; 68
	command healmorn                ; 69
	command healday                 ; 6a
	command healnite                ; 6b
	command hiddenpower             ; 6c
	command startrain               ; 6d
	command startsun                ; 6e
	command attackup                ; 6f
	command defenseup               ; 70
	command speedup                 ; 71
	command specialattackup         ; 72
	command specialdefenseup        ; 73
	command accuracyup              ; 74
	command evasionup               ; 75
	command attackup2               ; 76
	command defenseup2              ; 77
	command speedup2                ; 78
	command specialattackup2        ; 79
	command specialdefenseup2       ; 7a
	command accuracyup2             ; 7b
	command evasionup2              ; 7c
	command attackdown              ; 7d
	command defensedown             ; 7e
	command speeddown               ; 7f
	command specialattackdown       ; 80
	command specialdefensedown      ; 81
	command accuracydown            ; 82
	command evasiondown             ; 83
	command attackdown2             ; 84
	command defensedown2            ; 85
	command speeddown2              ; 86
	command specialattackdown2      ; 87
	command specialdefensedown2     ; 88
	command accuracydown2           ; 89
	command evasiondown2            ; 8a
	command statupmessage           ; 8b
	command statdownmessage         ; 8c
	command statupfailtext          ; 8d
	command statdownfailtext        ; 8e
	command effectchance            ; 8f
	command statdownanim            ; 90
	command statupanim              ; 91
	command switchturn              ; 92
	enum skip                       ; 93
	enum skip                       ; 94
	command rage                    ; 95
	command doubleflyingdamage      ; 96
	command doubleundergrounddamage ; 97
	command checkfuturesight        ; 98
	command futuresight             ; 99
	command doubleminimizedamage    ; 9a
	command skipsuncharge           ; 9b
	command thunderaccuracy         ; 9c
	command teleport                ; 9d
	enum skip                       ; 9e
	command resettypematchup        ; 9f
	command allstatsup              ; a0
	command raisesubnoanim          ; a1
	command lowersubnoanim          ; a2
	command clearmissdamage         ; a3
	command movedelay               ; a4
	command hittarget               ; a5
	command tristatuschance         ; a6
	command supereffectivelooptext  ; a7
	command startloop               ; a8
	command curl                    ; a9
	command lavapool                ; aa
	command metallurgy              ; ab
	command vaporize                ; ac
	command prismspray              ; ad
	command freezeburnchance        ; ae
	command naturepower             ; af
	command checkpowder             ; b0
	command painsplit               ; b1
	command bellydrum               ; b2
	command dragondance             ; b3
	command growth                  ; b4
	command defrostfoe              ; b5
	command laughinggas             ; b6

	enum_start -1, -1
	command endmove
	command endturn
